[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = tests
markers =
    integration: mark a test as an integration test
    slow: mark a test as slow
    asyncio: mark test as asyncio test
addopts = --strict-markers
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning
log_cli = true
log_cli_level = INFO
