"""Create initial database schema

Revision ID: 1d8602a08136
Revises:
Create Date: 2025-07-10 19:48:29.512466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d8602a08136'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'fields',
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('question', sa.String(), nullable=False),
        sa.Column('placeholder', sa.String(), nullable=True),
        sa.Column('is_required', sa.Boolean(), nullable=True),
        sa.Column('options', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('validation_rules', sa.JSON(), nullable=True),
        sa.Column('ai_suggestions', sa.JSON(), nullable=True),
        sa.Column('category', sa.String(), nullable=True),
        sa.Column('label', sa.String(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'users',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('role', sa.String(), nullable=False),
        sa.Column('organization_id', sa.String(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
    )
    op.create_index(
        'idx_users_email_prefix',
        'users',
        ['email'],
        unique=False,
        postgresql_ops={'email': 'text_pattern_ops'},
    )
    op.create_index(
        'idx_users_email_trgm',
        'users',
        ['email'],
        unique=False,
        postgresql_using='gin',
        postgresql_ops={'email': 'gin_trgm_ops'},
    )
    op.create_index(
        'idx_users_name_prefix',
        'users',
        ['name'],
        unique=False,
        postgresql_ops={'name': 'text_pattern_ops'},
    )
    op.create_index(
        'idx_users_name_trgm',
        'users',
        ['name'],
        unique=False,
        postgresql_using='gin',
        postgresql_ops={'name': 'gin_trgm_ops'},
    )
    op.create_table(
        'action_plans',
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('progress', sa.Integer(), nullable=True),
        sa.Column('start_date', sa.DateTime(), nullable=True),
        sa.Column('end_date', sa.DateTime(), nullable=True),
        sa.Column('recurring_pattern', sa.String(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'groups',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('tag', sa.String(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('created_by_id', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['created_by_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_groups_created_by', 'groups', ['created_by_id'], unique=False)
    op.create_table(
        'notification_devices',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('onesignal_player_id', sa.String(), nullable=False),
        sa.Column('device_type', sa.String(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('onesignal_player_id'),
    )
    op.create_index(
        'idx_notification_devices_user_id',
        'notification_devices',
        ['user_id'],
        unique=False,
    )
    op.create_table(
        'notification_preferences',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('feedback_reminders', sa.Boolean(), nullable=True),
        sa.Column('group_updates', sa.Boolean(), nullable=True),
        sa.Column('action_items', sa.Boolean(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id'),
    )
    op.create_index(
        'idx_notification_preferences_user_id',
        'notification_preferences',
        ['user_id'],
        unique=False,
    )
    op.create_table(
        'notifications',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('data', sa.JSON(), nullable=True),
        sa.Column('is_read', sa.Boolean(), nullable=True),
        sa.Column('read_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'idx_notifications_created_at', 'notifications', ['created_at'], unique=False
    )
    op.create_index(
        'idx_notifications_user_id_is_read',
        'notifications',
        ['user_id', 'is_read'],
        unique=False,
    )
    op.create_table(
        'templates',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('category', sa.String(), nullable=True),
        sa.Column('created_by_id', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['created_by_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'forms',
        sa.Column('template_id', sa.UUID(), nullable=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('context', sa.Text(), nullable=True),
        sa.Column('created_by_id', sa.UUID(), nullable=True),
        sa.Column('feedback_giver_persona', sa.String(), nullable=True),
        sa.Column('feedback_receiver_persona', sa.String(), nullable=True),
        sa.Column('respondents', sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column('priority', sa.Integer(), nullable=True),
        sa.Column(
            'status',
            sa.Enum(
                'DRAFT',
                'PUBLISHED',
                'ARCHIVED',
                name='formstatusenum',
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            'mode',
            sa.Enum(
                'COLLECT_FEEDBACK',
                'GIVE_FEEDBACK',
                name='formmodeenum',
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['created_by_id'],
            ['users.id'],
        ),
        sa.ForeignKeyConstraint(
            ['template_id'],
            ['templates.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_forms_created_by_id', 'forms', ['created_by_id'], unique=False)
    op.create_index('idx_forms_template_id', 'forms', ['template_id'], unique=False)
    op.create_table(
        'group_users',
        sa.Column('group_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ['group_id'],
            ['groups.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('group_id', 'user_id'),
    )
    op.create_index(
        'idx_group_users_composite',
        'group_users',
        ['group_id', 'user_id'],
        unique=False,
    )
    op.create_index(
        'idx_group_users_group_id', 'group_users', ['group_id'], unique=False
    )
    op.create_table(
        'form_fields',
        sa.Column('field_id', sa.UUID(), nullable=True),
        sa.Column('form_id', sa.UUID(), nullable=True),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('custom_question', sa.String(), nullable=True),
        sa.Column('custom_options', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('custom_label', sa.String(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['field_id'],
            ['fields.id'],
        ),
        sa.ForeignKeyConstraint(
            ['form_id'],
            ['forms.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'form_groups',
        sa.Column('form_id', sa.UUID(), nullable=False),
        sa.Column('group_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ['form_id'],
            ['forms.id'],
        ),
        sa.ForeignKeyConstraint(
            ['group_id'],
            ['groups.id'],
        ),
        sa.PrimaryKeyConstraint('form_id', 'group_id'),
    )
    op.create_table(
        'respondent_requests',
        sa.Column('form_id', sa.UUID(), nullable=True),
        sa.Column(
            'status',
            postgresql.ENUM(
                'Pending', 'Viewed', 'Completed', 'Declined', name='request_status_enum'
            ),
            nullable=True,
        ),
        sa.Column('requested_at', sa.DateTime(), nullable=False),
        sa.Column('reminder_sent', sa.Boolean(), nullable=True),
        sa.Column('reminder_count', sa.Integer(), nullable=True),
        sa.Column('last_reminder_at', sa.DateTime(), nullable=True),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['form_id'],
            ['forms.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'submissions',
        sa.Column('form_id', sa.UUID(), nullable=True),
        sa.Column('respondent_id', sa.UUID(), nullable=True),
        sa.Column('submitted_at', sa.DateTime(), nullable=False),
        sa.Column('values', sa.JSON(), nullable=False),
        sa.Column('receiver_id', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['form_id'],
            ['forms.id'],
        ),
        sa.ForeignKeyConstraint(
            ['receiver_id'],
            ['users.id'],
        ),
        sa.ForeignKeyConstraint(
            ['respondent_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'action_items',
        sa.Column('submission_id', sa.UUID(), nullable=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('priority', sa.Integer(), nullable=True),
        sa.Column('category', sa.String(), nullable=True),
        sa.Column(
            'status',
            postgresql.ENUM(
                'New',
                'In Progress',
                'Completed',
                'Deferred',
                name='respondent_action_status_enum',
            ),
            nullable=True,
        ),
        sa.Column('due_date', sa.DateTime(), nullable=True),
        sa.Column('assignee_id', sa.UUID(), nullable=True),
        sa.Column('source', sa.String(), nullable=True),
        sa.Column('ai_confidence', sa.Integer(), nullable=True),
        sa.Column('is_completed', sa.Boolean(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['assignee_id'],
            ['users.id'],
        ),
        sa.ForeignKeyConstraint(
            ['submission_id'],
            ['submissions.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'action_plan_items',
        sa.Column('action_plan_id', sa.UUID(), nullable=False),
        sa.Column('action_item_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ['action_item_id'],
            ['action_items.id'],
        ),
        sa.ForeignKeyConstraint(
            ['action_plan_id'],
            ['action_plans.id'],
        ),
        sa.PrimaryKeyConstraint('action_plan_id', 'action_item_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_plan_items')
    op.drop_table('action_items')
    op.drop_table('submissions')
    op.drop_table('respondent_requests')
    op.drop_table('form_groups')
    op.drop_table('form_fields')
    op.drop_index('idx_group_users_group_id', table_name='group_users')
    op.drop_index('idx_group_users_composite', table_name='group_users')
    op.drop_table('group_users')
    op.drop_index('idx_forms_template_id', table_name='forms')
    op.drop_index('idx_forms_created_by_id', table_name='forms')
    op.drop_table('forms')
    op.drop_table('templates')
    op.drop_index('idx_notifications_user_id_is_read', table_name='notifications')
    op.drop_index('idx_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(
        'idx_notification_preferences_user_id', table_name='notification_preferences'
    )
    op.drop_table('notification_preferences')
    op.drop_index('idx_notification_devices_user_id', table_name='notification_devices')
    op.drop_table('notification_devices')
    op.drop_index('idx_groups_created_by', table_name='groups')
    op.drop_table('groups')
    op.drop_table('action_plans')
    op.drop_index(
        'idx_users_name_trgm',
        table_name='users',
        postgresql_using='gin',
        postgresql_ops={'name': 'gin_trgm_ops'},
    )
    op.drop_index(
        'idx_users_name_prefix',
        table_name='users',
        postgresql_ops={'name': 'text_pattern_ops'},
    )
    op.drop_index(
        'idx_users_email_trgm',
        table_name='users',
        postgresql_using='gin',
        postgresql_ops={'email': 'gin_trgm_ops'},
    )
    op.drop_index(
        'idx_users_email_prefix',
        table_name='users',
        postgresql_ops={'email': 'text_pattern_ops'},
    )
    op.drop_table('users')
    op.drop_table('fields')
    # ### end Alembic commands ###
