"""nuke user table

Revision ID: 1e758dd6f4ed
Revises: b857f814896c
Create Date: 2025-07-16 21:57:27.807955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e758dd6f4ed'
down_revision: Union[str, None] = 'b857f814896c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - MANUALLY REORDERED ###

    op.drop_constraint(
        'action_items_assignee_id_fkey', 'action_items', type_='foreignkey'
    )
    op.drop_constraint('action_plans_user_id_fkey', 'action_plans', type_='foreignkey')
    op.drop_constraint('forms_created_by_id_fkey', 'forms', type_='foreignkey')
    op.drop_constraint(
        'notification_devices_user_id_fkey', 'notification_devices', type_='foreignkey'
    )
    op.drop_constraint(
        'notification_preferences_user_id_fkey',
        'notification_preferences',
        type_='foreignkey',
    )
    op.drop_constraint(
        'notifications_user_id_fkey', 'notifications', type_='foreignkey'
    )
    op.drop_constraint(
        'respondent_requests_user_id_fkey', 'respondent_requests', type_='foreignkey'
    )
    op.drop_constraint(
        'submissions_receiver_id_fkey', 'submissions', type_='foreignkey'
    )
    op.drop_constraint(
        'submissions_respondent_id_fkey', 'submissions', type_='foreignkey'
    )
    op.drop_constraint('templates_created_by_id_fkey', 'templates', type_='foreignkey')

    op.drop_index('idx_group_users_composite', table_name='group_users')
    op.drop_index('idx_group_users_group_id', table_name='group_users')
    op.drop_table('group_users')

    op.drop_index('idx_users_email_prefix', table_name='users')
    op.drop_index('idx_users_email_trgm', table_name='users', postgresql_using='gin')
    op.drop_index('idx_users_name_prefix', table_name='users')
    op.drop_index('idx_users_name_trgm', table_name='users', postgresql_using='gin')
    op.drop_table('users')

    op.drop_index('idx_forms_created_by_id', table_name='forms')
    op.drop_index('idx_forms_template_id', table_name='forms')
    op.create_index(
        op.f('ix_forms_created_by_id'), 'forms', ['created_by_id'], unique=False
    )
    op.drop_index('idx_notification_devices_user_id', table_name='notification_devices')
    op.create_index(
        op.f('ix_notification_devices_user_id'),
        'notification_devices',
        ['user_id'],
        unique=False,
    )
    op.drop_index(
        'idx_notification_preferences_user_id', table_name='notification_preferences'
    )
    op.drop_index('idx_notifications_created_at', table_name='notifications')
    op.drop_index('idx_notifications_user_id_is_read', table_name='notifications')
    op.create_index(
        op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False
    )
    op.create_index(
        op.f('ix_templates_created_by_id'), 'templates', ['created_by_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        'templates_created_by_id_fkey', 'templates', 'users', ['created_by_id'], ['id']
    )
    op.drop_index(op.f('ix_templates_created_by_id'), table_name='templates')
    op.create_foreign_key(
        'submissions_respondent_id_fkey',
        'submissions',
        'users',
        ['respondent_id'],
        ['id'],
    )
    op.create_foreign_key(
        'submissions_receiver_id_fkey', 'submissions', 'users', ['receiver_id'], ['id']
    )
    op.create_foreign_key(
        'respondent_requests_user_id_fkey',
        'respondent_requests',
        'users',
        ['user_id'],
        ['id'],
    )
    op.create_foreign_key(
        'notifications_user_id_fkey', 'notifications', 'users', ['user_id'], ['id']
    )
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.create_index(
        'idx_notifications_user_id_is_read',
        'notifications',
        ['user_id', 'is_read'],
        unique=False,
    )
    op.create_index(
        'idx_notifications_created_at', 'notifications', ['created_at'], unique=False
    )
    op.create_foreign_key(
        'notification_preferences_user_id_fkey',
        'notification_preferences',
        'users',
        ['user_id'],
        ['id'],
    )
    op.create_index(
        'idx_notification_preferences_user_id',
        'notification_preferences',
        ['user_id'],
        unique=False,
    )
    op.create_foreign_key(
        'notification_devices_user_id_fkey',
        'notification_devices',
        'users',
        ['user_id'],
        ['id'],
    )
    op.drop_index(
        op.f('ix_notification_devices_user_id'), table_name='notification_devices'
    )
    op.create_index(
        'idx_notification_devices_user_id',
        'notification_devices',
        ['user_id'],
        unique=False,
    )
    op.create_foreign_key(
        'forms_created_by_id_fkey', 'forms', 'users', ['created_by_id'], ['id']
    )
    op.drop_index(op.f('ix_forms_created_by_id'), table_name='forms')
    op.create_index('idx_forms_template_id', 'forms', ['template_id'], unique=False)
    op.create_index('idx_forms_created_by_id', 'forms', ['created_by_id'], unique=False)
    op.create_foreign_key(
        'action_plans_user_id_fkey', 'action_plans', 'users', ['user_id'], ['id']
    )
    op.create_foreign_key(
        'action_items_assignee_id_fkey',
        'action_items',
        'users',
        ['assignee_id'],
        ['id'],
    )
    op.create_table(
        'users',
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('organization_id', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint('id', name='users_pkey'),
        sa.UniqueConstraint(
            'email',
            name='users_email_key',
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        'idx_users_name_trgm', 'users', ['name'], unique=False, postgresql_using='gin'
    )
    op.create_index('idx_users_name_prefix', 'users', ['name'], unique=False)
    op.create_index(
        'idx_users_email_trgm', 'users', ['email'], unique=False, postgresql_using='gin'
    )
    op.create_index('idx_users_email_prefix', 'users', ['email'], unique=False)
    op.create_table(
        'group_users',
        sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ['group_id'], ['groups.id'], name='group_users_group_id_fkey'
        ),
        sa.ForeignKeyConstraint(
            ['user_id'], ['users.id'], name='group_users_user_id_fkey'
        ),
        sa.PrimaryKeyConstraint('group_id', 'user_id', name='group_users_pkey'),
    )
    op.create_index(
        'idx_group_users_group_id', 'group_users', ['group_id'], unique=False
    )
    op.create_index(
        'idx_group_users_composite',
        'group_users',
        ['group_id', 'user_id'],
        unique=False,
    )
    # ### end Alembic commands ###
