"""inherit str for enum

Revision ID: 1ee9f4dd5f87
Revises: 40c7af2f45c3
Create Date: 2025-07-09 01:04:43.560166

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '1ee9f4dd5f87'
down_revision: Union[str, None] = '40c7af2f45c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
