"""form v2 public link

Revision ID: 20e8dad7b149
Revises: 26ae403d1f51
Create Date: 2025-11-10 18:18:45.846671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20e8dad7b149'
down_revision: Union[str, Sequence[str], None] = '26ae403d1f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms_v2', sa.Column('public_link', sa.String(length=16), nullable=False))
    op.create_index(op.f('ix_forms_v2_public_link'), 'forms_v2', ['public_link'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forms_v2_public_link'), table_name='forms_v2')
    op.drop_column('forms_v2', 'public_link')
    # ### end Alembic commands ###
