"""020 formv2

Revision ID: 26ae403d1f51
Revises: f342f5515364
Create Date: 2025-11-08 23:49:55.966753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26ae403d1f51'
down_revision: Union[str, Sequence[str], None] = 'f342f5515364'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms_v2',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('form_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forms_v2_created_at'), 'forms_v2', ['created_at'], unique=False)
    op.create_index(op.f('ix_forms_v2_deleted_at'), 'forms_v2', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_forms_v2_id'), 'forms_v2', ['id'], unique=False)
    op.create_index(op.f('ix_forms_v2_updated_at'), 'forms_v2', ['updated_at'], unique=False)
    op.create_table('form_fields_v2',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms_v2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_fields_v2_created_at'), 'form_fields_v2', ['created_at'], unique=False)
    op.create_index(op.f('ix_form_fields_v2_deleted_at'), 'form_fields_v2', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_form_fields_v2_form_id'), 'form_fields_v2', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_fields_v2_id'), 'form_fields_v2', ['id'], unique=False)
    op.create_index(op.f('ix_form_fields_v2_updated_at'), 'form_fields_v2', ['updated_at'], unique=False)
    op.drop_column('feature_request_feedback', 'implementation_status')
    op.drop_constraint(op.f('uq_usage_tracking'), 'usage_tracking', type_='unique')
    op.create_index(op.f('ix_usage_tracking_created_at'), 'usage_tracking', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_tracking_id'), 'usage_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_usage_tracking_updated_at'), 'usage_tracking', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_tracking_updated_at'), table_name='usage_tracking')
    op.drop_index(op.f('ix_usage_tracking_id'), table_name='usage_tracking')
    op.drop_index(op.f('ix_usage_tracking_created_at'), table_name='usage_tracking')
    op.create_unique_constraint(op.f('uq_usage_tracking'), 'usage_tracking', ['organization_id', 'resource_type', 'period_start'], postgresql_nulls_not_distinct=False)
    op.add_column('feature_request_feedback', sa.Column('implementation_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_form_fields_v2_updated_at'), table_name='form_fields_v2')
    op.drop_index(op.f('ix_form_fields_v2_id'), table_name='form_fields_v2')
    op.drop_index(op.f('ix_form_fields_v2_form_id'), table_name='form_fields_v2')
    op.drop_index(op.f('ix_form_fields_v2_deleted_at'), table_name='form_fields_v2')
    op.drop_index(op.f('ix_form_fields_v2_created_at'), table_name='form_fields_v2')
    op.drop_table('form_fields_v2')
    op.drop_index(op.f('ix_forms_v2_updated_at'), table_name='forms_v2')
    op.drop_index(op.f('ix_forms_v2_id'), table_name='forms_v2')
    op.drop_index(op.f('ix_forms_v2_deleted_at'), table_name='forms_v2')
    op.drop_index(op.f('ix_forms_v2_created_at'), table_name='forms_v2')
    op.drop_table('forms_v2')
    # ### end Alembic commands ###
