"""change targeting rules from dict to list

Revision ID: 2e3f371c009b
Revises: 9dc669cd84cf
Create Date: 2025-08-08 12:50:43.589104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e3f371c009b'
down_revision: Union[str, Sequence[str], None] = '9dc669cd84cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # This is a data migration to change targeting_rules from dict to list format
    # Update existing widgets with targeting_rules
    op.execute("""
        UPDATE widgets 
        SET targeting_rules = '[]'::jsonb 
        WHERE targeting_rules IS NULL
    """)
    
    op.execute("""
        UPDATE widgets 
        SET targeting_rules = 
            CASE 
                WHEN jsonb_typeof(targeting_rules) = 'object' 
                THEN jsonb_build_array(targeting_rules)
                ELSE targeting_rules 
            END
        WHERE targeting_rules IS NOT NULL 
        AND jsonb_typeof(targeting_rules) != 'array'
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert targeting_rules back from array to object format
    op.execute("""
        UPDATE widgets 
        SET targeting_rules = 
            CASE 
                WHEN jsonb_typeof(targeting_rules) = 'array' 
                    AND jsonb_array_length(targeting_rules) > 0
                THEN targeting_rules->0
                ELSE '{}'::jsonb
            END
        WHERE targeting_rules IS NOT NULL
    """)
    # ### end Alembic commands ###