"""change targeting rules from dict to list

Revision ID: 2e3f371c009b
Revises: 06778ed93e41
Create Date: 2025-08-08 12:50:43.589104

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '2e3f371c009b'
down_revision: Union[str, Sequence[str], None] = '06778ed93e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
