"""add form expiry datetime

Revision ID: 40c7af2f45c3
Revises: 43cc2803289a
Create Date: 2025-07-08 00:40:10.359151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40c7af2f45c3'
down_revision: Union[str, None] = '1d8602a08136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'expires_at')
    # ### end Alembic commands ###
