"""add index for assignee ID in action item schema

Revision ID: 4d2f95717477
Revises: 1ee9f4dd5f87
Create Date: 2025-07-09 22:21:29.704125

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '4d2f95717477'
down_revision: Union[str, None] = '1ee9f4dd5f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f('ix_action_items_assignee_id'),
        'action_items',
        ['assignee_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_action_items_assignee_id'), table_name='action_items')
    # ### end Alembic commands ###
