"""update_widget_position_enum_add_mid_positions

Revision ID: 5f028e3852a1
Revises: a234bcdb1baa
Create Date: 2025-09-05 09:16:31.886589

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f028e3852a1'
down_revision: Union[str, Sequence[str], None] = 'a234bcdb1baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widgets', 'is_active')

    # Update widget position enum to include new mid positions
    op.execute("ALTER TYPE widgetposition ADD VALUE 'MID_RIGHT'")
    op.execute("ALTER TYPE widgetposition ADD VALUE 'MID_LEFT'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'widgets',
        sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
