"""Add project role to invitation

Revision ID: 621f64158e4f
Revises: add_form_usage_tracking_trigger
Create Date: 2025-11-23 15:04:55.420209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '621f64158e4f'
down_revision: Union[str, Sequence[str], None] = 'add_form_usage_tracking_trigger'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('project_role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'project_role')
    # ### end Alembic commands ###
