"""Add roadmap tables

Revision ID: 64caa391325b
Revises: 86cdee4025b8
Create Date: 2025-08-10 11:59:57.956514

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64caa391325b'
down_revision: Union[str, Sequence[str], None] = 'f62f34ac6069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'roadmaps',
        sa.Column('project_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('is_public', sa.Boolean(), nullable=False),
        sa.Column('public_slug', sa.String(length=100), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_roadmaps_created_at'), 'roadmaps', ['created_at'], unique=False
    )
    op.create_index(
        op.f('ix_roadmaps_deleted_at'), 'roadmaps', ['deleted_at'], unique=False
    )
    op.create_index(op.f('ix_roadmaps_id'), 'roadmaps', ['id'], unique=False)
    op.create_index(
        op.f('ix_roadmaps_project_id'), 'roadmaps', ['project_id'], unique=True
    )
    op.create_index(
        op.f('ix_roadmaps_public_slug'), 'roadmaps', ['public_slug'], unique=True
    )
    op.create_index(
        op.f('ix_roadmaps_updated_at'), 'roadmaps', ['updated_at'], unique=False
    )
    op.create_table(
        'roadmap_columns',
        sa.Column('roadmap_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('color', sa.String(length=7), nullable=False),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('roadmap_id', 'name', name='uq_roadmap_column_name'),
    )
    op.create_index(
        op.f('ix_roadmap_columns_created_at'),
        'roadmap_columns',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_columns_deleted_at'),
        'roadmap_columns',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_columns_id'), 'roadmap_columns', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_roadmap_columns_roadmap_id'),
        'roadmap_columns',
        ['roadmap_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_columns_updated_at'),
        'roadmap_columns',
        ['updated_at'],
        unique=False,
    )
    op.create_table(
        'roadmap_features',
        sa.Column('column_id', sa.UUID(), nullable=False),
        sa.Column('feedback_id', sa.UUID(), nullable=True),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('vote_count', sa.Integer(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['column_id'], ['roadmap_columns.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_roadmap_features_column_id'),
        'roadmap_features',
        ['column_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_features_created_at'),
        'roadmap_features',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_features_deleted_at'),
        'roadmap_features',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_features_feedback_id'),
        'roadmap_features',
        ['feedback_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_features_id'), 'roadmap_features', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_roadmap_features_updated_at'),
        'roadmap_features',
        ['updated_at'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmap_features_updated_at'), table_name='roadmap_features')
    op.drop_index(op.f('ix_roadmap_features_id'), table_name='roadmap_features')
    op.drop_index(
        op.f('ix_roadmap_features_feedback_id'), table_name='roadmap_features'
    )
    op.drop_index(op.f('ix_roadmap_features_deleted_at'), table_name='roadmap_features')
    op.drop_index(op.f('ix_roadmap_features_created_at'), table_name='roadmap_features')
    op.drop_index(op.f('ix_roadmap_features_column_id'), table_name='roadmap_features')
    op.drop_table('roadmap_features')
    op.drop_index(op.f('ix_roadmap_columns_updated_at'), table_name='roadmap_columns')
    op.drop_index(op.f('ix_roadmap_columns_roadmap_id'), table_name='roadmap_columns')
    op.drop_index(op.f('ix_roadmap_columns_id'), table_name='roadmap_columns')
    op.drop_index(op.f('ix_roadmap_columns_deleted_at'), table_name='roadmap_columns')
    op.drop_index(op.f('ix_roadmap_columns_created_at'), table_name='roadmap_columns')
    op.drop_table('roadmap_columns')
    op.drop_index(op.f('ix_roadmaps_updated_at'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_public_slug'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_project_id'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_id'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_deleted_at'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_created_at'), table_name='roadmaps')
    op.drop_table('roadmaps')
    # ### end Alembic commands ###
