"""Fix user relationship and add mapping type

Revision ID: 71ae4d3c95d7
Revises: 6c9f9aeb85ac
Create Date: 2025-08-12 21:16:48.782478

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '71ae4d3c95d7'
down_revision: Union[str, Sequence[str], None] = '6c9f9aeb85ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
