"""add_feedback_conversion_tracking

Revision ID: 73238fea42a8
Revises: 5be8741c7307
Create Date: 2025-08-23 22:42:57.228340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73238fea42a8'
down_revision: Union[str, Sequence[str], None] = '5be8741c7307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Define all the new ENUM type objects at the top
mapping_type_enum = sa.Enum(
    'FEEDBACK_TO_ISSUE', 'FEATURE_TO_EPIC', 'PROJECT_TO_PROJECT', name='mappingtype'
)
integration_type_enum = sa.Enum(
    'JIRA', 'GITHUB', 'LINEAR', 'SLACK', 'DISCORD', 'WEBHOOK', name='integrationtype'
)
integration_status_enum = sa.Enum(
    'ACTIVE', 'INACTIVE', 'ERROR', 'PENDING', name='integrationstatus'
)
webhook_status_enum = sa.Enum('ACTIVE', 'INACTIVE', 'FAILED', name='webhookstatus')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create all ENUM types in the database FIRST
    mapping_type_enum.create(op.get_bind())
    integration_type_enum.create(op.get_bind())
    integration_status_enum.create(op.get_bind())
    webhook_status_enum.create(op.get_bind())

    op.drop_index(op.f('ix_feedback_votes_created_at'), table_name='feedback_votes')
    op.drop_index(op.f('ix_feedback_votes_deleted_at'), table_name='feedback_votes')
    op.drop_index(op.f('ix_feedback_votes_feedback_id'), table_name='feedback_votes')
    op.drop_index(op.f('ix_feedback_votes_id'), table_name='feedback_votes')
    op.drop_index(op.f('ix_feedback_votes_updated_at'), table_name='feedback_votes')
    op.drop_table('feedback_votes')
    op.drop_column('bug_report_feedback', 'environment_info')
    op.drop_column('bug_report_feedback', 'attachments')
    op.drop_column('feature_request_feedback', 'estimated_effort')
    op.drop_column('feature_request_feedback', 'impact_score')
    op.drop_column('feature_request_feedback', 'business_value')
    op.add_column(
        'feedback', sa.Column('converted_to_action_item_id ', sa.UUID(), nullable=True)
    )
    op.add_column(
        'feedback', sa.Column('conversion_date', sa.DateTime(), nullable=True)
    )
    op.add_column('feedback', sa.Column('conversion_notes', sa.Text(), nullable=True))
    op.add_column('feedback', sa.Column('is_actionable', sa.Boolean(), nullable=True))
    op.alter_column(
        'feedback',
        'feedback_votes',
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text('0'),
    )
    op.create_foreign_key(
        None, 'feedback', 'roadmap_features', ['converted_to_action_item_id '], ['id']
    )
    op.add_column(
        'feedback_forms', sa.Column('form_type', sa.String(length=50), nullable=False)
    )

    # Use the predefined enum variables here
    op.add_column(
        'integration_mappings',
        sa.Column('mapping_type', mapping_type_enum, nullable=False),
    )
    op.add_column(
        'integration_mappings', sa.Column('internal_id', sa.UUID(), nullable=False)
    )
    op.add_column(
        'integration_mappings',
        sa.Column('external_id', sa.String(length=255), nullable=False),
    )
    op.add_column(
        'integration_mappings',
        sa.Column('external_url', sa.String(length=500), nullable=True),
    )
    op.add_column(
        'integration_mappings',
        sa.Column(
            'mapping_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
    )
    op.add_column(
        'integration_mappings', sa.Column('is_active', sa.Boolean(), nullable=False)
    )
    op.drop_column('integration_mappings', 'entity_type')
    op.drop_column('integration_mappings', 'external_entity_id')
    op.drop_column('integration_mappings', 'external_entity_url')
    op.drop_column('integration_mappings', 'local_entity_id')

    # Use the predefined enum variables here
    op.add_column(
        'integrations',
        sa.Column('integration_type', integration_type_enum, nullable=False),
    )
    op.add_column(
        'integrations', sa.Column('status', integration_status_enum, nullable=False)
    )
    op.add_column(
        'integrations',
        sa.Column('auth_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.add_column(
        'integrations', sa.Column('sync_enabled', sa.Boolean(), nullable=False)
    )
    op.add_column('integrations', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('integrations', sa.Column('created_by', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'integrations', 'users', ['created_by'], ['id'])
    op.drop_column('integrations', 'type')
    op.create_index(
        op.f('ix_organizations_created_by'),
        'organizations',
        ['created_by'],
        unique=False,
    )
    op.drop_constraint(
        'organizations_created_by_fkey', 'organizations', type_='foreignkey'
    )  # Adjusted to remove op.f() for existing constraint
    op.create_foreign_key(
        None, 'organizations', 'users', ['created_by'], ['id'], ondelete='SET NULL'
    )
    op.drop_column('review_feedback', 'reviewer_location')
    op.drop_column('review_feedback', 'review_categories')
    op.drop_column('review_feedback', 'published_at')
    op.drop_column('review_feedback', 'moderation_status')
    op.add_column(
        'roadmap_columns', sa.Column('status', sa.String(length=50), nullable=False)
    )
    op.add_column(
        'roadmap_features',
        sa.Column('submitter_name', sa.String(length=255), nullable=True),
    )
    op.add_column(
        'roadmap_features',
        sa.Column('submitter_email', sa.String(length=255), nullable=True),
    )
    op.add_column('roadmaps', sa.Column('logo_url', sa.Text(), nullable=True))
    op.add_column(
        'webhooks',
        sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )

    # Use the predefined enum variable here
    op.add_column('webhooks', sa.Column('status', webhook_status_enum, nullable=False))
    op.add_column('webhooks', sa.Column('secret', sa.String(length=255), nullable=True))
    op.add_column('webhooks', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column(
        'webhooks', sa.Column('timeout_seconds', sa.Integer(), nullable=False)
    )
    op.add_column(
        'webhooks', sa.Column('last_triggered_at', sa.String(), nullable=True)
    )
    op.add_column(
        'webhooks', sa.Column('last_response_code', sa.Integer(), nullable=True)
    )
    op.add_column('webhooks', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('webhooks', sa.Column('created_by', sa.UUID(), nullable=False))
    op.alter_column(
        'webhooks',
        'url',
        existing_type=sa.TEXT(),
        type_=sa.String(length=500),
        existing_nullable=False,
    )
    op.alter_column(
        'webhooks',
        'events',
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        postgresql_using='to_jsonb(events)',
    )
    op.create_foreign_key(None, 'webhooks', 'users', ['created_by'], ['id'])
    op.drop_column('webhooks', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'webhooks',
        sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        'webhooks_created_by_fkey', 'webhooks', type_='foreignkey'
    )  # Adjusted to be specific
    op.alter_column(
        'webhooks',
        'events',
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.ARRAY(sa.VARCHAR()),
        existing_nullable=False,
        postgresql_using='events::jsonb',
    )
    op.alter_column(
        'webhooks',
        'url',
        existing_type=sa.String(length=500),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_column('webhooks', 'created_by')
    op.drop_column('webhooks', 'error_message')
    op.drop_column('webhooks', 'last_response_code')
    op.drop_column('webhooks', 'last_triggered_at')
    op.drop_column('webhooks', 'timeout_seconds')
    op.drop_column('webhooks', 'retry_count')
    op.drop_column('webhooks', 'secret')
    op.drop_column('webhooks', 'status')
    op.drop_column('webhooks', 'headers')
    op.drop_column('roadmaps', 'logo_url')
    op.drop_column('roadmap_features', 'submitter_email')
    op.drop_column('roadmap_features', 'submitter_name')
    op.drop_column('roadmap_columns', 'status')
    op.add_column(
        'review_feedback',
        sa.Column(
            'moderation_status',
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'review_feedback',
        sa.Column(
            'published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        'review_feedback',
        sa.Column(
            'review_categories',
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'review_feedback',
        sa.Column(
            'reviewer_location',
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(
        'organizations_created_by_fkey', 'organizations', type_='foreignkey'
    )  # Adjusted to be specific
    op.create_foreign_key(
        'organizations_created_by_fkey',
        'organizations',
        'users',
        ['created_by'],
        ['id'],
    )
    op.drop_index(op.f('ix_organizations_created_by'), table_name='organizations')
    op.add_column(
        'integrations',
        sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        'integrations_created_by_fkey', 'integrations', type_='foreignkey'
    )  # Adjusted to be specific
    op.drop_column('integrations', 'created_by')
    op.drop_column('integrations', 'error_message')
    op.drop_column('integrations', 'sync_enabled')
    op.drop_column('integrations', 'auth_data')
    op.drop_column('integrations', 'status')
    op.drop_column('integrations', 'integration_type')
    op.add_column(
        'integration_mappings',
        sa.Column('local_entity_id', sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        'integration_mappings',
        sa.Column('external_entity_url', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'integration_mappings',
        sa.Column(
            'external_entity_id',
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        'integration_mappings',
        sa.Column(
            'entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.drop_column('integration_mappings', 'is_active')
    op.drop_column('integration_mappings', 'mapping_metadata')
    op.drop_column('integration_mappings', 'external_url')
    op.drop_column('integration_mappings', 'external_id')
    op.drop_column('integration_mappings', 'internal_id')
    op.drop_column('integration_mappings', 'mapping_type')
    op.drop_column('feedback_forms', 'form_type')
    op.drop_constraint(
        'feedback_converted_to_action_item_id _fkey', 'feedback', type_='foreignkey'
    )  # Adjusted to be specific
    op.alter_column(
        'feedback',
        'feedback_votes',
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_server_default=sa.text('0'),
    )
    op.drop_column('feedback', 'is_actionable')
    op.drop_column('feedback', 'conversion_notes')
    op.drop_column('feedback', 'conversion_date')
    op.drop_column('feedback', 'converted_to_action_item_id ')
    op.add_column(
        'feature_request_feedback',
        sa.Column('business_value', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'feature_request_feedback',
        sa.Column('impact_score', sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'feature_request_feedback',
        sa.Column(
            'estimated_effort',
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'bug_report_feedback',
        sa.Column(
            'attachments',
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'bug_report_feedback',
        sa.Column(
            'environment_info',
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table(
        'feedback_votes',
        sa.Column('feedback_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            'session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            'vote_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False
        ),
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'deleted_at',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ['feedback_id'], ['feedback.id'], name='feedback_votes_feedback_id_fkey'
        ),
        sa.ForeignKeyConstraint(
            ['user_id'], ['users.id'], name='feedback_votes_user_id_fkey'
        ),
        sa.PrimaryKeyConstraint('id', name='feedback_votes_pkey'),
    )
    op.create_index(
        op.f('ix_feedback_votes_updated_at'),
        'feedback_votes',
        ['updated_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_feedback_votes_id'), 'feedback_votes', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_feedback_votes_feedback_id'),
        'feedback_votes',
        ['feedback_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_feedback_votes_deleted_at'),
        'feedback_votes',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_feedback_votes_created_at'),
        'feedback_votes',
        ['created_at'],
        unique=False,
    )

    # Drop all the ENUM types from the database LAST
    mapping_type_enum.drop(op.get_bind())
    integration_type_enum.drop(op.get_bind())
    integration_status_enum.drop(op.get_bind())
    webhook_status_enum.drop(op.get_bind())

    # ### end Alembic commands ###
