"""Add RoadmmapTag and subdomain field

Revision ID: 7dc12f41798b
Revises:
Create Date: 2025-08-20 21:04:04.884818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dc12f41798b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('avatar_url', sa.String(), nullable=True),
        sa.Column('company_name', sa.String(length=255), nullable=True),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('timezone', sa.String(length=50), nullable=False),
        sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('first_login_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
        sa.Column('user_type', sa.Enum('SOLO', 'TEAM', name='usertype'), nullable=True),
        sa.Column(
            'user_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            'app_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_updated_at'), 'users', ['updated_at'], unique=False)
    op.create_table(
        'notifications',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('entity_type', sa.String(length=50), nullable=True),
        sa.Column('entity_id', sa.UUID(), nullable=True),
        sa.Column('is_read', sa.Boolean(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_notifications_created_at'),
        'notifications',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_notifications_deleted_at'),
        'notifications',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(
        op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False
    )
    op.create_index(
        op.f('ix_notifications_updated_at'),
        'notifications',
        ['updated_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False
    )
    op.create_table(
        'organizations',
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('slug', sa.String(length=100), nullable=False),
        sa.Column('description', sa.String(length=500), nullable=True),
        sa.Column('subscription_tier', sa.String(length=50), nullable=False),
        sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('created_by', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_organizations_created_at'),
        'organizations',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_organizations_created_by'),
        'organizations',
        ['created_by'],
        unique=False,
    )
    op.create_index(
        op.f('ix_organizations_deleted_at'),
        'organizations',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(
        op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True
    )
    op.create_index(
        op.f('ix_organizations_updated_at'),
        'organizations',
        ['updated_at'],
        unique=False,
    )
    op.create_table(
        'user_onboarding',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('has_created_project', sa.Boolean(), nullable=False),
        sa.Column('has_created_widget', sa.Boolean(), nullable=False),
        sa.Column('has_received_first_feedback', sa.Boolean(), nullable=False),
        sa.Column('company_size', sa.String(length=50), nullable=True),
        sa.Column('use_case', sa.String(length=100), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_user_onboarding_created_at'),
        'user_onboarding',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_user_onboarding_deleted_at'),
        'user_onboarding',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_user_onboarding_id'), 'user_onboarding', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_user_onboarding_updated_at'),
        'user_onboarding',
        ['updated_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_user_onboarding_user_id'), 'user_onboarding', ['user_id'], unique=True
    )
    op.create_table(
        'invitation_tasks',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('organization_id', sa.UUID(), nullable=True),
        sa.Column('total_count', sa.Integer(), nullable=False),
        sa.Column('processed_count', sa.Integer(), nullable=True),
        sa.Column('success_count', sa.Integer(), nullable=True),
        sa.Column('failed_count', sa.Integer(), nullable=True),
        sa.Column(
            'status',
            sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='taskstatus'),
            nullable=False,
        ),
        sa.Column('results', sa.JSON(), nullable=True),
        sa.Column('error', sa.String(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['organization_id'], ['organizations.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_invitation_tasks_created_at'),
        'invitation_tasks',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_invitation_tasks_updated_at'),
        'invitation_tasks',
        ['updated_at'],
        unique=False,
    )
    op.create_table(
        'organization_members',
        sa.Column('organization_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'role',
            sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='organizationrole'),
            nullable=False,
        ),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['organization_id'], ['organizations.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'organization_id', 'user_id', name='uq_organization_member'
        ),
    )
    op.create_index(
        op.f('ix_organization_members_created_at'),
        'organization_members',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_organization_members_deleted_at'),
        'organization_members',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_organization_members_id'), 'organization_members', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_organization_members_organization_id'),
        'organization_members',
        ['organization_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_organization_members_updated_at'),
        'organization_members',
        ['updated_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_organization_members_user_id'),
        'organization_members',
        ['user_id'],
        unique=False,
    )
    op.create_table(
        'projects',
        sa.Column('organization_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('display_name', sa.String(length=255), nullable=False),
        sa.Column('slug', sa.String(length=100), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('logo_url', sa.String(), nullable=True),
        sa.Column('main_website_url', sa.String(), nullable=True),
        sa.Column('public_reviews_enabled', sa.Boolean(), nullable=False),
        sa.Column('public_reviews_url', sa.String(length=100), nullable=True),
        sa.Column('allow_new_review_submissions', sa.Boolean(), nullable=False),
        sa.Column('default_review_sort_order', sa.String(length=20), nullable=False),
        sa.Column('seo_page_title_suffix', sa.String(length=100), nullable=True),
        sa.Column('seo_meta_description', sa.String(length=160), nullable=True),
        sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['organization_id'], ['organizations.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'organization_id', 'slug', name='uq_project_organization_slug'
        ),
    )
    op.create_index(
        op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(
        op.f('ix_projects_organization_id'),
        'projects',
        ['organization_id'],
        unique=False,
    )
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=False)
    op.create_index(
        op.f('ix_projects_updated_at'), 'projects', ['updated_at'], unique=False
    )
    op.create_table(
        'feedback_forms',
        sa.Column('project_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('form_type', sa.String(length=50), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_feedback_forms_created_at'),
        'feedback_forms',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_feedback_forms_deleted_at'),
        'feedback_forms',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_feedback_forms_id'), 'feedback_forms', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_feedback_forms_updated_at'),
        'feedback_forms',
        ['updated_at'],
        unique=False,
    )
    op.create_table(
        'integrations',
        sa.Column('project_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column(
            'integration_type',
            sa.Enum(
                'JIRA',
                'GITHUB',
                'LINEAR',
                'SLACK',
                'DISCORD',
                'WEBHOOK',
                name='integrationtype',
            ),
            nullable=False,
        ),
        sa.Column(
            'status',
            sa.Enum('ACTIVE', 'INACTIVE', 'ERROR', 'PENDING', name='integrationstatus'),
            nullable=False,
        ),
        sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('auth_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('sync_enabled', sa.Boolean(), nullable=False),
        sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['created_by'],
            ['users.id'],
        ),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_integrations_created_at'), 'integrations', ['created_at'], unique=False
    )
    op.create_index(
        op.f('ix_integrations_deleted_at'), 'integrations', ['deleted_at'], unique=False
    )
    op.create_index(op.f('ix_integrations_id'), 'integrations', ['id'], unique=False)
    op.create_index(
        op.f('ix_integrations_project_id'), 'integrations', ['project_id'], unique=False
    )
    op.create_index(
        op.f('ix_integrations_updated_at'), 'integrations', ['updated_at'], unique=False
    )
    op.create_table(
        'invitations',
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('role', sa.String(), nullable=False),
        sa.Column('organization_id', sa.UUID(), nullable=True),
        sa.Column('project_id', sa.UUID(), nullable=True),
        sa.Column('invited_by', sa.UUID(), nullable=False),
        sa.Column('token', sa.String(), nullable=False),
        sa.Column(
            'status',
            sa.Enum(
                'PENDING', 'ACCEPTED', 'EXPIRED', 'CANCELLED', name='invitationstatus'
            ),
            nullable=False,
        ),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('accepted_at', sa.DateTime(), nullable=True),
        sa.Column('accepted_by', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(
            ['organization_id'], ['organizations.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_invitations_created_at'), 'invitations', ['created_at'], unique=False
    )
    op.create_index(
        op.f('ix_invitations_deleted_at'), 'invitations', ['deleted_at'], unique=False
    )
    op.create_index(
        op.f('ix_invitations_email'), 'invitations', ['email'], unique=False
    )
    op.create_index(op.f('ix_invitations_id'), 'invitations', ['id'], unique=False)
    op.create_index(op.f('ix_invitations_token'), 'invitations', ['token'], unique=True)
    op.create_index(
        op.f('ix_invitations_updated_at'), 'invitations', ['updated_at'], unique=False
    )
    op.create_table(
        'project_members',
        sa.Column('project_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column(
            'role',
            sa.Enum('ADMIN', 'EDITOR', 'VIEWER', name='projectrole'),
            nullable=False,
        ),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member'),
    )
    op.create_index(
        op.f('ix_project_members_created_at'),
        'project_members',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_project_members_deleted_at'),
        'project_members',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_project_members_id'), 'project_members', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_project_members_project_id'),
        'project_members',
        ['project_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_project_members_updated_at'),
        'project_members',
        ['updated_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False
    )
    op.create_table(
        'roadmaps',
        sa.Column('project_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('is_public', sa.Boolean(), nullable=False),
        sa.Column('public_slug', sa.String(length=100), nullable=False),
        sa.Column('subdomain', sa.String(length=100), nullable=True),
        sa.Column('logo_url', sa.Text(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_roadmaps_created_at'), 'roadmaps', ['created_at'], unique=False
    )
    op.create_index(
        op.f('ix_roadmaps_deleted_at'), 'roadmaps', ['deleted_at'], unique=False
    )
    op.create_index(op.f('ix_roadmaps_id'), 'roadmaps', ['id'], unique=False)
    op.create_index(
        op.f('ix_roadmaps_project_id'), 'roadmaps', ['project_id'], unique=True
    )
    op.create_index(
        op.f('ix_roadmaps_public_slug'), 'roadmaps', ['public_slug'], unique=True
    )
    op.create_index(
        op.f('ix_roadmaps_subdomain'), 'roadmaps', ['subdomain'], unique=True
    )
    op.create_index(
        op.f('ix_roadmaps_updated_at'), 'roadmaps', ['updated_at'], unique=False
    )
    op.create_table(
        'webhooks',
        sa.Column('project_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('url', sa.String(length=500), nullable=False),
        sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            'status',
            sa.Enum('ACTIVE', 'INACTIVE', 'FAILED', name='webhookstatus'),
            nullable=False,
        ),
        sa.Column('secret', sa.String(length=255), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.Column('timeout_seconds', sa.Integer(), nullable=False),
        sa.Column('last_triggered_at', sa.String(), nullable=True),
        sa.Column('last_response_code', sa.Integer(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_by', sa.UUID(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['created_by'],
            ['users.id'],
        ),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_webhooks_created_at'), 'webhooks', ['created_at'], unique=False
    )
    op.create_index(
        op.f('ix_webhooks_deleted_at'), 'webhooks', ['deleted_at'], unique=False
    )
    op.create_index(op.f('ix_webhooks_id'), 'webhooks', ['id'], unique=False)
    op.create_index(
        op.f('ix_webhooks_project_id'), 'webhooks', ['project_id'], unique=False
    )
    op.create_index(
        op.f('ix_webhooks_updated_at'), 'webhooks', ['updated_at'], unique=False
    )
    op.create_table(
        'widgets',
        sa.Column('project_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column(
            'widget_type',
            sa.Enum(
                'FEEDBACK',
                'SURVEY',
                'REVIEW',
                'BUG_REPORT',
                'FEATURE_REQUEST',
                'NPS',
                name='widgettype',
            ),
            nullable=False,
        ),
        sa.Column(
            'status',
            sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED', name='widgetstatus'),
            nullable=True,
        ),
        sa.Column(
            'configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            'theme_configuration',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column(
            'targeting_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column('embed_code', sa.Text(), nullable=True),
        sa.Column('public_key', sa.String(length=255), nullable=True),
        sa.Column(
            'position',
            sa.Enum(
                'BOTTOM_RIGHT',
                'BOTTOM_LEFT',
                'TOP_RIGHT',
                'TOP_LEFT',
                'CENTER',
                name='widgetposition',
            ),
            nullable=True,
        ),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['project_id'],
            ['projects.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_widgets_created_at'), 'widgets', ['created_at'], unique=False
    )
    op.create_index(
        op.f('ix_widgets_deleted_at'), 'widgets', ['deleted_at'], unique=False
    )
    op.create_index(op.f('ix_widgets_id'), 'widgets', ['id'], unique=False)
    op.create_index(
        op.f('ix_widgets_public_key'), 'widgets', ['public_key'], unique=True
    )
    op.create_index(
        op.f('ix_widgets_updated_at'), 'widgets', ['updated_at'], unique=False
    )
    op.create_table(
        'feedback',
        sa.Column('widget_id', sa.UUID(), nullable=False),
        sa.Column('project_id', sa.UUID(), nullable=False),
        sa.Column('form_id', sa.UUID(), nullable=True),
        sa.Column(
            'feedback_type',
            sa.Enum(
                'GENERAL',
                'SURVEY',
                'REVIEW',
                'BUG_REPORT',
                'FEATURE_REQUEST',
                'NPS',
                'CSAT',
                'CES',
                name='feedbacktype',
            ),
            nullable=False,
        ),
        sa.Column(
            'status',
            sa.Enum(
                'NEW',
                'IN_PROGRESS',
                'RESOLVED',
                'REJECTED',
                'ARCHIVED',
                name='feedbackstatus',
            ),
            nullable=True,
        ),
        sa.Column(
            'priority',
            sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='feedbackpriority'),
            nullable=True,
        ),
        sa.Column('title', sa.String(length=500), nullable=True),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('rating', sa.Integer(), nullable=True),
        sa.Column(
            'feedback_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('submitter_name', sa.String(length=255), nullable=True),
        sa.Column('submitter_email', sa.String(length=320), nullable=True),
        sa.Column('submitter_id', sa.String(length=255), nullable=True),
        sa.Column('ip_address', postgresql.INET(), nullable=True),
        sa.Column('user_agent', sa.Text(), nullable=True),
        sa.Column(
            'browser_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column('is_anonymous', sa.Boolean(), nullable=True),
        sa.Column('is_internal', sa.Boolean(), nullable=True),
        sa.Column('is_spam', sa.Boolean(), nullable=True),
        sa.Column('is_flagged', sa.Boolean(), nullable=True),
        sa.Column('assigned_to_user_id', sa.UUID(), nullable=True),
        sa.Column('resolved_at', sa.DateTime(), nullable=True),
        sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
        sa.Column('resolution_notes', sa.Text(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['assigned_to_user_id'],
            ['users.id'],
        ),
        sa.ForeignKeyConstraint(
            ['form_id'],
            ['feedback_forms.id'],
        ),
        sa.ForeignKeyConstraint(
            ['project_id'],
            ['projects.id'],
        ),
        sa.ForeignKeyConstraint(
            ['resolved_by_user_id'],
            ['users.id'],
        ),
        sa.ForeignKeyConstraint(
            ['widget_id'],
            ['widgets.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False
    )
    op.create_index(
        op.f('ix_feedback_deleted_at'), 'feedback', ['deleted_at'], unique=False
    )
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_index(
        op.f('ix_feedback_updated_at'), 'feedback', ['updated_at'], unique=False
    )
    op.create_table(
        'form_fields',
        sa.Column('form_id', sa.UUID(), nullable=False),
        sa.Column('field_type', sa.String(length=50), nullable=False),
        sa.Column('field_key', sa.String(length=100), nullable=False),
        sa.Column('label', sa.String(length=255), nullable=False),
        sa.Column('is_required', sa.Boolean(), nullable=False),
        sa.Column(
            'validation_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('order_index', sa.Integer(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['form_id'], ['feedback_forms.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_form_fields_created_at'), 'form_fields', ['created_at'], unique=False
    )
    op.create_index(
        op.f('ix_form_fields_deleted_at'), 'form_fields', ['deleted_at'], unique=False
    )
    op.create_index(
        op.f('ix_form_fields_form_id'), 'form_fields', ['form_id'], unique=False
    )
    op.create_index(op.f('ix_form_fields_id'), 'form_fields', ['id'], unique=False)
    op.create_index(
        op.f('ix_form_fields_updated_at'), 'form_fields', ['updated_at'], unique=False
    )
    op.create_table(
        'integration_mappings',
        sa.Column('integration_id', sa.UUID(), nullable=False),
        sa.Column(
            'mapping_type',
            sa.Enum(
                'FEEDBACK_TO_ISSUE',
                'FEATURE_TO_EPIC',
                'PROJECT_TO_PROJECT',
                name='mappingtype',
            ),
            nullable=False,
        ),
        sa.Column('internal_id', sa.UUID(), nullable=False),
        sa.Column('external_id', sa.String(length=255), nullable=False),
        sa.Column('external_url', sa.String(length=500), nullable=True),
        sa.Column(
            'mapping_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column('sync_status', sa.String(length=50), nullable=False),
        sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['integration_id'], ['integrations.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_integration_mappings_created_at'),
        'integration_mappings',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_integration_mappings_deleted_at'),
        'integration_mappings',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_integration_mappings_id'), 'integration_mappings', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_integration_mappings_integration_id'),
        'integration_mappings',
        ['integration_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_integration_mappings_updated_at'),
        'integration_mappings',
        ['updated_at'],
        unique=False,
    )
    op.create_table(
        'pending_members',
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('role', sa.String(), nullable=False),
        sa.Column('organization_id', sa.UUID(), nullable=True),
        sa.Column('project_id', sa.UUID(), nullable=True),
        sa.Column('invitation_id', sa.UUID(), nullable=False),
        sa.Column('added_by', sa.UUID(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(
            ['invitation_id'], ['invitations.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['organization_id'], ['organizations.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_pending_members_created_at'),
        'pending_members',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_pending_members_deleted_at'),
        'pending_members',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_pending_members_email'), 'pending_members', ['email'], unique=False
    )
    op.create_index(
        op.f('ix_pending_members_id'), 'pending_members', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_pending_members_updated_at'),
        'pending_members',
        ['updated_at'],
        unique=False,
    )
    op.create_table(
        'roadmap_columns',
        sa.Column('roadmap_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('color', sa.String(length=7), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('roadmap_id', 'name', name='uq_roadmap_column_name'),
    )
    op.create_index(
        op.f('ix_roadmap_columns_created_at'),
        'roadmap_columns',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_columns_deleted_at'),
        'roadmap_columns',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_columns_id'), 'roadmap_columns', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_roadmap_columns_roadmap_id'),
        'roadmap_columns',
        ['roadmap_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_columns_updated_at'),
        'roadmap_columns',
        ['updated_at'],
        unique=False,
    )
    op.create_table(
        'roadmap_tags',
        sa.Column('roadmap_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('color', sa.String(length=7), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('roadmap_id', 'name', name='uq_roadmap_tag_name'),
    )
    op.create_index(
        op.f('ix_roadmap_tags_created_at'), 'roadmap_tags', ['created_at'], unique=False
    )
    op.create_index(
        op.f('ix_roadmap_tags_deleted_at'), 'roadmap_tags', ['deleted_at'], unique=False
    )
    op.create_index(op.f('ix_roadmap_tags_id'), 'roadmap_tags', ['id'], unique=False)
    op.create_index(
        op.f('ix_roadmap_tags_roadmap_id'), 'roadmap_tags', ['roadmap_id'], unique=False
    )
    op.create_index(
        op.f('ix_roadmap_tags_updated_at'), 'roadmap_tags', ['updated_at'], unique=False
    )
    op.create_table(
        'bug_report_feedback',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('severity_level', sa.String(length=50), nullable=True),
        sa.Column('steps_to_reproduce', sa.Text(), nullable=True),
        sa.Column('expected_behavior', sa.Text(), nullable=True),
        sa.Column('actual_behavior', sa.Text(), nullable=True),
        sa.Column(
            'environment_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['id'],
            ['feedback.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'feature_request_feedback',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('use_case', sa.Text(), nullable=True),
        sa.Column('business_value', sa.Text(), nullable=True),
        sa.Column('effort_estimate', sa.String(length=50), nullable=True),
        sa.Column('impact_score', sa.Integer(), nullable=True),
        sa.Column('implementation_status', sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(
            ['id'],
            ['feedback.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'feedback_comments',
        sa.Column('feedback_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('comment_text', sa.Text(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['feedback_id'],
            ['feedback.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_feedback_comments_created_at'),
        'feedback_comments',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_feedback_comments_deleted_at'),
        'feedback_comments',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_feedback_comments_feedback_id'),
        'feedback_comments',
        ['feedback_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_feedback_comments_id'), 'feedback_comments', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_feedback_comments_updated_at'),
        'feedback_comments',
        ['updated_at'],
        unique=False,
    )
    op.create_table(
        'feedback_votes',
        sa.Column('feedback_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('session_id', sa.String(length=255), nullable=True),
        sa.Column('vote_type', sa.String(length=10), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['feedback_id'],
            ['feedback.id'],
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_feedback_votes_created_at'),
        'feedback_votes',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_feedback_votes_deleted_at'),
        'feedback_votes',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_feedback_votes_feedback_id'),
        'feedback_votes',
        ['feedback_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_feedback_votes_id'), 'feedback_votes', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_feedback_votes_updated_at'),
        'feedback_votes',
        ['updated_at'],
        unique=False,
    )
    op.create_table(
        'review_feedback',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('overall_rating', sa.Integer(), nullable=True),
        sa.Column('pros', sa.Text(), nullable=True),
        sa.Column('cons', sa.Text(), nullable=True),
        sa.Column('is_published', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ['id'],
            ['feedback.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'roadmap_features',
        sa.Column('column_id', sa.UUID(), nullable=False),
        sa.Column('feedback_id', sa.UUID(), nullable=True),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('vote_count', sa.Integer(), nullable=False),
        sa.Column('submitter_name', sa.String(length=255), nullable=True),
        sa.Column('submitter_email', sa.String(length=255), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['column_id'], ['roadmap_columns.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_roadmap_features_column_id'),
        'roadmap_features',
        ['column_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_features_created_at'),
        'roadmap_features',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_features_deleted_at'),
        'roadmap_features',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_features_feedback_id'),
        'roadmap_features',
        ['feedback_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_features_id'), 'roadmap_features', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_roadmap_features_updated_at'),
        'roadmap_features',
        ['updated_at'],
        unique=False,
    )
    op.create_table(
        'survey_feedback',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('survey_type', sa.String(length=50), nullable=True),
        sa.Column('score', sa.Integer(), nullable=True),
        sa.Column(
            'response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['id'],
            ['feedback.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'roadmap_feature_tags',
        sa.Column('feature_id', sa.UUID(), nullable=False),
        sa.Column('tag_id', sa.UUID(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['feature_id'], ['roadmap_features.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['tag_id'], ['roadmap_tags.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('feature_id', 'tag_id', name='uq_feature_tag'),
    )
    op.create_index(
        op.f('ix_roadmap_feature_tags_created_at'),
        'roadmap_feature_tags',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_feature_tags_deleted_at'),
        'roadmap_feature_tags',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_feature_tags_feature_id'),
        'roadmap_feature_tags',
        ['feature_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_feature_tags_id'), 'roadmap_feature_tags', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_roadmap_feature_tags_tag_id'),
        'roadmap_feature_tags',
        ['tag_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_feature_tags_updated_at'),
        'roadmap_feature_tags',
        ['updated_at'],
        unique=False,
    )
    op.create_table(
        'roadmap_item_assignments',
        sa.Column('roadmap_feature_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('role', sa.String(length=50), nullable=False),
        sa.Column('assigned_by', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['assigned_by'],
            ['users.id'],
        ),
        sa.ForeignKeyConstraint(
            ['roadmap_feature_id'], ['roadmap_features.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'roadmap_feature_id', 'user_id', name='uq_roadmap_assignment'
        ),
    )
    op.create_index(
        op.f('ix_roadmap_item_assignments_created_at'),
        'roadmap_item_assignments',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_item_assignments_deleted_at'),
        'roadmap_item_assignments',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_item_assignments_id'),
        'roadmap_item_assignments',
        ['id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_item_assignments_roadmap_feature_id'),
        'roadmap_item_assignments',
        ['roadmap_feature_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_item_assignments_updated_at'),
        'roadmap_item_assignments',
        ['updated_at'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_roadmap_item_assignments_updated_at'),
        table_name='roadmap_item_assignments',
    )
    op.drop_index(
        op.f('ix_roadmap_item_assignments_roadmap_feature_id'),
        table_name='roadmap_item_assignments',
    )
    op.drop_index(
        op.f('ix_roadmap_item_assignments_id'), table_name='roadmap_item_assignments'
    )
    op.drop_index(
        op.f('ix_roadmap_item_assignments_deleted_at'),
        table_name='roadmap_item_assignments',
    )
    op.drop_index(
        op.f('ix_roadmap_item_assignments_created_at'),
        table_name='roadmap_item_assignments',
    )
    op.drop_table('roadmap_item_assignments')
    op.drop_index(
        op.f('ix_roadmap_feature_tags_updated_at'), table_name='roadmap_feature_tags'
    )
    op.drop_index(
        op.f('ix_roadmap_feature_tags_tag_id'), table_name='roadmap_feature_tags'
    )
    op.drop_index(op.f('ix_roadmap_feature_tags_id'), table_name='roadmap_feature_tags')
    op.drop_index(
        op.f('ix_roadmap_feature_tags_feature_id'), table_name='roadmap_feature_tags'
    )
    op.drop_index(
        op.f('ix_roadmap_feature_tags_deleted_at'), table_name='roadmap_feature_tags'
    )
    op.drop_index(
        op.f('ix_roadmap_feature_tags_created_at'), table_name='roadmap_feature_tags'
    )
    op.drop_table('roadmap_feature_tags')
    op.drop_table('survey_feedback')
    op.drop_index(op.f('ix_roadmap_features_updated_at'), table_name='roadmap_features')
    op.drop_index(op.f('ix_roadmap_features_id'), table_name='roadmap_features')
    op.drop_index(
        op.f('ix_roadmap_features_feedback_id'), table_name='roadmap_features'
    )
    op.drop_index(op.f('ix_roadmap_features_deleted_at'), table_name='roadmap_features')
    op.drop_index(op.f('ix_roadmap_features_created_at'), table_name='roadmap_features')
    op.drop_index(op.f('ix_roadmap_features_column_id'), table_name='roadmap_features')
    op.drop_table('roadmap_features')
    op.drop_table('review_feedback')
    op.drop_index(op.f('ix_feedback_votes_updated_at'), table_name='feedback_votes')
    op.drop_index(op.f('ix_feedback_votes_id'), table_name='feedback_votes')
    op.drop_index(op.f('ix_feedback_votes_feedback_id'), table_name='feedback_votes')
    op.drop_index(op.f('ix_feedback_votes_deleted_at'), table_name='feedback_votes')
    op.drop_index(op.f('ix_feedback_votes_created_at'), table_name='feedback_votes')
    op.drop_table('feedback_votes')
    op.drop_index(
        op.f('ix_feedback_comments_updated_at'), table_name='feedback_comments'
    )
    op.drop_index(op.f('ix_feedback_comments_id'), table_name='feedback_comments')
    op.drop_index(
        op.f('ix_feedback_comments_feedback_id'), table_name='feedback_comments'
    )
    op.drop_index(
        op.f('ix_feedback_comments_deleted_at'), table_name='feedback_comments'
    )
    op.drop_index(
        op.f('ix_feedback_comments_created_at'), table_name='feedback_comments'
    )
    op.drop_table('feedback_comments')
    op.drop_table('feature_request_feedback')
    op.drop_table('bug_report_feedback')
    op.drop_index(op.f('ix_roadmap_tags_updated_at'), table_name='roadmap_tags')
    op.drop_index(op.f('ix_roadmap_tags_roadmap_id'), table_name='roadmap_tags')
    op.drop_index(op.f('ix_roadmap_tags_id'), table_name='roadmap_tags')
    op.drop_index(op.f('ix_roadmap_tags_deleted_at'), table_name='roadmap_tags')
    op.drop_index(op.f('ix_roadmap_tags_created_at'), table_name='roadmap_tags')
    op.drop_table('roadmap_tags')
    op.drop_index(op.f('ix_roadmap_columns_updated_at'), table_name='roadmap_columns')
    op.drop_index(op.f('ix_roadmap_columns_roadmap_id'), table_name='roadmap_columns')
    op.drop_index(op.f('ix_roadmap_columns_id'), table_name='roadmap_columns')
    op.drop_index(op.f('ix_roadmap_columns_deleted_at'), table_name='roadmap_columns')
    op.drop_index(op.f('ix_roadmap_columns_created_at'), table_name='roadmap_columns')
    op.drop_table('roadmap_columns')
    op.drop_index(op.f('ix_pending_members_updated_at'), table_name='pending_members')
    op.drop_index(op.f('ix_pending_members_id'), table_name='pending_members')
    op.drop_index(op.f('ix_pending_members_email'), table_name='pending_members')
    op.drop_index(op.f('ix_pending_members_deleted_at'), table_name='pending_members')
    op.drop_index(op.f('ix_pending_members_created_at'), table_name='pending_members')
    op.drop_table('pending_members')
    op.drop_index(
        op.f('ix_integration_mappings_updated_at'), table_name='integration_mappings'
    )
    op.drop_index(
        op.f('ix_integration_mappings_integration_id'),
        table_name='integration_mappings',
    )
    op.drop_index(op.f('ix_integration_mappings_id'), table_name='integration_mappings')
    op.drop_index(
        op.f('ix_integration_mappings_deleted_at'), table_name='integration_mappings'
    )
    op.drop_index(
        op.f('ix_integration_mappings_created_at'), table_name='integration_mappings'
    )
    op.drop_table('integration_mappings')
    op.drop_index(op.f('ix_form_fields_updated_at'), table_name='form_fields')
    op.drop_index(op.f('ix_form_fields_id'), table_name='form_fields')
    op.drop_index(op.f('ix_form_fields_form_id'), table_name='form_fields')
    op.drop_index(op.f('ix_form_fields_deleted_at'), table_name='form_fields')
    op.drop_index(op.f('ix_form_fields_created_at'), table_name='form_fields')
    op.drop_table('form_fields')
    op.drop_index(op.f('ix_feedback_updated_at'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_deleted_at'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_widgets_updated_at'), table_name='widgets')
    op.drop_index(op.f('ix_widgets_public_key'), table_name='widgets')
    op.drop_index(op.f('ix_widgets_id'), table_name='widgets')
    op.drop_index(op.f('ix_widgets_deleted_at'), table_name='widgets')
    op.drop_index(op.f('ix_widgets_created_at'), table_name='widgets')
    op.drop_table('widgets')
    op.drop_index(op.f('ix_webhooks_updated_at'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_project_id'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_id'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_deleted_at'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_created_at'), table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_roadmaps_updated_at'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_subdomain'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_public_slug'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_project_id'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_id'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_deleted_at'), table_name='roadmaps')
    op.drop_index(op.f('ix_roadmaps_created_at'), table_name='roadmaps')
    op.drop_table('roadmaps')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_updated_at'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_deleted_at'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_created_at'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_invitations_updated_at'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_token'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_deleted_at'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_created_at'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_integrations_updated_at'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_project_id'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_id'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_deleted_at'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_created_at'), table_name='integrations')
    op.drop_table('integrations')
    op.drop_index(op.f('ix_feedback_forms_updated_at'), table_name='feedback_forms')
    op.drop_index(op.f('ix_feedback_forms_id'), table_name='feedback_forms')
    op.drop_index(op.f('ix_feedback_forms_deleted_at'), table_name='feedback_forms')
    op.drop_index(op.f('ix_feedback_forms_created_at'), table_name='feedback_forms')
    op.drop_table('feedback_forms')
    op.drop_index(op.f('ix_projects_updated_at'), table_name='projects')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(
        op.f('ix_organization_members_user_id'), table_name='organization_members'
    )
    op.drop_index(
        op.f('ix_organization_members_updated_at'), table_name='organization_members'
    )
    op.drop_index(
        op.f('ix_organization_members_organization_id'),
        table_name='organization_members',
    )
    op.drop_index(op.f('ix_organization_members_id'), table_name='organization_members')
    op.drop_index(
        op.f('ix_organization_members_deleted_at'), table_name='organization_members'
    )
    op.drop_index(
        op.f('ix_organization_members_created_at'), table_name='organization_members'
    )
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_invitation_tasks_updated_at'), table_name='invitation_tasks')
    op.drop_index(op.f('ix_invitation_tasks_created_at'), table_name='invitation_tasks')
    op.drop_table('invitation_tasks')
    op.drop_index(op.f('ix_user_onboarding_user_id'), table_name='user_onboarding')
    op.drop_index(op.f('ix_user_onboarding_updated_at'), table_name='user_onboarding')
    op.drop_index(op.f('ix_user_onboarding_id'), table_name='user_onboarding')
    op.drop_index(op.f('ix_user_onboarding_deleted_at'), table_name='user_onboarding')
    op.drop_index(op.f('ix_user_onboarding_created_at'), table_name='user_onboarding')
    op.drop_table('user_onboarding')
    op.drop_index(op.f('ix_organizations_updated_at'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_deleted_at'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_created_by'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_created_at'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_updated_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_deleted_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_users_updated_at'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
