"""empty message

Revision ID: 86cdee4025b8
Revises: f62f34ac6069
Create Date: 2025-08-10 11:34:07.140288

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '86cdee4025b8'
down_revision: Union[str, Sequence[str], None] = 'f62f34ac6069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
