"""rename_integration_mapping_metadata_field_to_avoid_sqlalchemy_conflict

Revision ID: 906d4095f729
Revises: e436f1776c02
Create Date: 2025-08-12 03:38:12.075388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '906d4095f729'
down_revision: Union[str, Sequence[str], None] = 'e436f1776c02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bug_report_feedback', 'severity_level',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='feedbackpriority'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_column('bug_report_feedback', 'attachments')
    op.add_column('feature_request_feedback', sa.Column('effort_estimate', sa.String(length=50), nullable=True))
    op.drop_column('feature_request_feedback', 'estimated_effort')
    op.add_column('feedback_forms', sa.Column('form_type', sa.String(length=50), nullable=False))
    op.add_column('integration_mappings', sa.Column('mapping_type', sa.Enum('FEEDBACK_TO_ISSUE', 'FEATURE_TO_EPIC', 'PROJECT_TO_PROJECT', name='mappingtype'), nullable=False))
    op.add_column('integration_mappings', sa.Column('internal_id', sa.UUID(), nullable=False))
    op.add_column('integration_mappings', sa.Column('external_id', sa.String(length=255), nullable=False))
    op.add_column('integration_mappings', sa.Column('external_url', sa.String(length=500), nullable=True))
    op.add_column('integration_mappings', sa.Column('mapping_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('integration_mappings', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('integration_mappings', 'entity_type')
    op.drop_column('integration_mappings', 'local_entity_id')
    op.drop_column('integration_mappings', 'external_entity_url')
    op.drop_column('integration_mappings', 'external_entity_id')
    op.add_column('integrations', sa.Column('integration_type', sa.Enum('JIRA', 'GITHUB', 'LINEAR', 'SLACK', 'DISCORD', 'WEBHOOK', name='integrationtype'), nullable=False))
    op.add_column('integrations', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ERROR', 'PENDING', name='integrationstatus'), nullable=False))
    op.add_column('integrations', sa.Column('auth_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('integrations', sa.Column('sync_enabled', sa.Boolean(), nullable=False))
    op.add_column('integrations', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('integrations', sa.Column('created_by', sa.UUID(), nullable=False))
    op.create_foreign_key('integrations_created_by_fkey', 'integrations', 'users', ['created_by'], ['id'])
    op.drop_column('integrations', 'type')
    op.add_column('review_feedback', sa.Column('pros', sa.Text(), nullable=True))
    op.add_column('review_feedback', sa.Column('cons', sa.Text(), nullable=True))
    op.drop_column('review_feedback', 'reviewer_location')
    op.drop_column('review_feedback', 'review_categories')
    op.drop_column('review_feedback', 'published_at')
    op.drop_column('review_feedback', 'moderation_status')
    op.add_column('webhooks', sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('webhooks', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'FAILED', name='webhookstatus'), nullable=False))
    op.add_column('webhooks', sa.Column('secret', sa.String(length=255), nullable=True))
    op.add_column('webhooks', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('webhooks', sa.Column('timeout_seconds', sa.Integer(), nullable=False))
    op.add_column('webhooks', sa.Column('last_triggered_at', sa.String(), nullable=True))
    op.add_column('webhooks', sa.Column('last_response_code', sa.Integer(), nullable=True))
    op.add_column('webhooks', sa.Column('error_message', sa.Text(), nullable=True))
    op.add_column('webhooks', sa.Column('created_by', sa.UUID(), nullable=False))
    op.alter_column('webhooks', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('webhooks', 'events',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_foreign_key('webhooks_created_by_fkey', 'webhooks', 'users', ['created_by'], ['id'])
    op.drop_column('webhooks', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhooks', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint('webhooks_created_by_fkey', 'webhooks', type_='foreignkey')
    op.alter_column('webhooks', 'events',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=False)
    op.alter_column('webhooks', 'url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('webhooks', 'created_by')
    op.drop_column('webhooks', 'error_message')
    op.drop_column('webhooks', 'last_response_code')
    op.drop_column('webhooks', 'last_triggered_at')
    op.drop_column('webhooks', 'timeout_seconds')
    op.drop_column('webhooks', 'retry_count')
    op.drop_column('webhooks', 'secret')
    op.drop_column('webhooks', 'status')
    op.drop_column('webhooks', 'headers')
    op.add_column('review_feedback', sa.Column('moderation_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('review_feedback', sa.Column('published_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('review_feedback', sa.Column('review_categories', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('review_feedback', sa.Column('reviewer_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('review_feedback', 'cons')
    op.drop_column('review_feedback', 'pros')
    op.add_column('integrations', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint('integrations_created_by_fkey', 'integrations', type_='foreignkey')
    op.drop_column('integrations', 'created_by')
    op.drop_column('integrations', 'error_message')
    op.drop_column('integrations', 'sync_enabled')
    op.drop_column('integrations', 'auth_data')
    op.drop_column('integrations', 'status')
    op.drop_column('integrations', 'integration_type')
    op.add_column('integration_mappings', sa.Column('external_entity_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('integration_mappings', sa.Column('external_entity_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('integration_mappings', sa.Column('local_entity_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('integration_mappings', sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('integration_mappings', 'is_active')
    op.drop_column('integration_mappings', 'mapping_metadata')
    op.drop_column('integration_mappings', 'external_url')
    op.drop_column('integration_mappings', 'external_id')
    op.drop_column('integration_mappings', 'internal_id')
    op.drop_column('integration_mappings', 'mapping_type')
    op.drop_column('feedback_forms', 'form_type')
    op.add_column('feature_request_feedback', sa.Column('estimated_effort', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('feature_request_feedback', 'effort_estimate')
    op.add_column('bug_report_feedback', sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.alter_column('bug_report_feedback', 'severity_level',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='feedbackpriority'),
               existing_nullable=True)
    # ### end Alembic commands ###
