"""add RESPONDED to form enums

Revision ID: 923f5c3fd9d3
Revises: a74472244fca
Create Date: 2025-07-17 20:28:54.761491

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '923f5c3fd9d3'
down_revision: Union[str, None] = 'a74472244fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
