"""Add extensible integration tracking for action items

Revision ID: 9bafe7731a2e
Revises: e90827417a49
Create Date: 2025-08-27 18:43:52.063282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9bafe7731a2e'
down_revision: Union[str, Sequence[str], None] = 'e90827417a49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # First, drop the foreign key constraints that reference roadmap_features
    op.drop_constraint(
        'feedback_converted_to_action_item_id _fkey', 'feedback', type_='foreignkey'
    )
    op.drop_constraint(
        'roadmap_item_assignments_roadmap_feature_id_fkey',
        'roadmap_item_assignments',
        type_='foreignkey',
    )

    # Create the new tables
    op.create_table(
        'roadmap_action_items',
        sa.Column('column_id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('vote_count', sa.Integer(), nullable=False),
        sa.Column('submitter_name', sa.String(length=255), nullable=True),
        sa.Column('submitter_email', sa.String(length=255), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['column_id'], ['roadmap_columns.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_roadmap_action_items_column_id'),
        'roadmap_action_items',
        ['column_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_action_items_created_at'),
        'roadmap_action_items',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_action_items_deleted_at'),
        'roadmap_action_items',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_action_items_id'), 'roadmap_action_items', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_roadmap_action_items_updated_at'),
        'roadmap_action_items',
        ['updated_at'],
        unique=False,
    )

    op.create_table(
        'roadmap_action_item_integrations',
        sa.Column('action_item_id', sa.UUID(), nullable=False),
        sa.Column('integration_id', sa.UUID(), nullable=False),
        sa.Column('external_id', sa.String(length=255), nullable=False),
        sa.Column('external_url', sa.String(length=500), nullable=True),
        sa.Column('external_status', sa.String(length=100), nullable=True),
        sa.Column(
            'integration_metadata',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('sync_status', sa.String(length=50), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['action_item_id'], ['roadmap_action_items.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['integration_id'], ['integrations.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint(
            'action_item_id', 'integration_id', name='uq_action_item_integration'
        ),
    )
    op.create_index(
        'idx_action_item_integration_external_id',
        'roadmap_action_item_integrations',
        ['external_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_action_item_integrations_action_item_id'),
        'roadmap_action_item_integrations',
        ['action_item_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_action_item_integrations_created_at'),
        'roadmap_action_item_integrations',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_action_item_integrations_deleted_at'),
        'roadmap_action_item_integrations',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_action_item_integrations_external_id'),
        'roadmap_action_item_integrations',
        ['external_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_action_item_integrations_id'),
        'roadmap_action_item_integrations',
        ['id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_action_item_integrations_integration_id'),
        'roadmap_action_item_integrations',
        ['integration_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_action_item_integrations_updated_at'),
        'roadmap_action_item_integrations',
        ['updated_at'],
        unique=False,
    )

    op.create_table(
        'roadmap_action_item_tags',
        sa.Column('action_item_id', sa.UUID(), nullable=False),
        sa.Column('tag_id', sa.UUID(), nullable=False),
        sa.Column('priority', sa.String(length=20), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['action_item_id'], ['roadmap_action_items.id'], ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['tag_id'], ['roadmap_tags.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('action_item_id', 'tag_id', name='uq_action_item_tag'),
    )
    op.create_index(
        op.f('ix_roadmap_action_item_tags_action_item_id'),
        'roadmap_action_item_tags',
        ['action_item_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_action_item_tags_created_at'),
        'roadmap_action_item_tags',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_action_item_tags_deleted_at'),
        'roadmap_action_item_tags',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_action_item_tags_id'),
        'roadmap_action_item_tags',
        ['id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_action_item_tags_tag_id'),
        'roadmap_action_item_tags',
        ['tag_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_action_item_tags_updated_at'),
        'roadmap_action_item_tags',
        ['updated_at'],
        unique=False,
    )

    # Now drop the old tables
    op.drop_index(
        op.f('ix_roadmap_feature_tags_created_at'), table_name='roadmap_feature_tags'
    )
    op.drop_index(
        op.f('ix_roadmap_feature_tags_deleted_at'), table_name='roadmap_feature_tags'
    )
    op.drop_index(
        op.f('ix_roadmap_feature_tags_feature_id'), table_name='roadmap_feature_tags'
    )
    op.drop_index(op.f('ix_roadmap_feature_tags_id'), table_name='roadmap_feature_tags')
    op.drop_index(
        op.f('ix_roadmap_feature_tags_tag_id'), table_name='roadmap_feature_tags'
    )
    op.drop_index(
        op.f('ix_roadmap_feature_tags_updated_at'), table_name='roadmap_feature_tags'
    )
    op.drop_table('roadmap_feature_tags')

    op.drop_index(op.f('ix_roadmap_features_column_id'), table_name='roadmap_features')
    op.drop_index(op.f('ix_roadmap_features_created_at'), table_name='roadmap_features')
    op.drop_index(op.f('ix_roadmap_features_deleted_at'), table_name='roadmap_features')
    op.drop_index(op.f('ix_roadmap_features_id'), table_name='roadmap_features')
    op.drop_index(op.f('ix_roadmap_features_updated_at'), table_name='roadmap_features')
    op.drop_table('roadmap_features')

    # Update foreign key references to point to new table
    op.create_foreign_key(
        None,
        'feedback',
        'roadmap_action_items',
        ['converted_to_action_item_id'],
        ['id'],
    )

    op.add_column(
        'roadmap_item_assignments',
        sa.Column('roadmap_action_item_id', sa.UUID(), nullable=False),
    )
    op.drop_index(
        op.f('ix_roadmap_item_assignments_roadmap_feature_id'),
        table_name='roadmap_item_assignments',
    )
    op.drop_constraint(
        op.f('uq_roadmap_assignment'), 'roadmap_item_assignments', type_='unique'
    )
    op.create_unique_constraint(
        'uq_roadmap_assignment',
        'roadmap_item_assignments',
        ['roadmap_action_item_id', 'user_id'],
    )
    op.create_index(
        op.f('ix_roadmap_item_assignments_roadmap_action_item_id'),
        'roadmap_item_assignments',
        ['roadmap_action_item_id'],
        unique=False,
    )
    op.create_foreign_key(
        None,
        'roadmap_item_assignments',
        'roadmap_action_items',
        ['roadmap_action_item_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.drop_column('roadmap_item_assignments', 'roadmap_feature_id')

    op.create_index(
        op.f('ix_feature_votes_created_at'),
        'feature_votes',
        ['created_at'],
        unique=False,
    )
    op.create_index(op.f('ix_feature_votes_id'), 'feature_votes', ['id'], unique=False)

    op.alter_column(
        'widgets',
        'published_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'widgets',
        'published_at',
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.add_column(
        'roadmap_item_assignments',
        sa.Column('roadmap_feature_id', sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, 'roadmap_item_assignments', type_='foreignkey')
    op.create_foreign_key(
        op.f('roadmap_item_assignments_roadmap_feature_id_fkey'),
        'roadmap_item_assignments',
        'roadmap_features',
        ['roadmap_feature_id'],
        ['id'],
        ondelete='CASCADE',
    )
    op.drop_index(
        op.f('ix_roadmap_item_assignments_roadmap_action_item_id'),
        table_name='roadmap_item_assignments',
    )
    op.drop_constraint(
        'uq_roadmap_assignment', 'roadmap_item_assignments', type_='unique'
    )
    op.create_unique_constraint(
        op.f('uq_roadmap_assignment'),
        'roadmap_item_assignments',
        ['roadmap_feature_id', 'user_id'],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(
        op.f('ix_roadmap_item_assignments_roadmap_feature_id'),
        'roadmap_item_assignments',
        ['roadmap_feature_id'],
        unique=False,
    )
    op.drop_column('roadmap_item_assignments', 'roadmap_action_item_id')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.create_foreign_key(
        op.f('feedback_converted_to_action_item_id _fkey'),
        'feedback',
        'roadmap_features',
        ['converted_to_action_item_id'],
        ['id'],
    )
    op.drop_index(op.f('ix_feature_votes_id'), table_name='feature_votes')
    op.drop_index(op.f('ix_feature_votes_created_at'), table_name='feature_votes')
    op.create_table(
        'roadmap_features',
        sa.Column('column_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('vote_count', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'deleted_at',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'submitter_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            'submitter_email',
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ['column_id'],
            ['roadmap_columns.id'],
            name='roadmap_features_column_id_fkey',
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name='roadmap_features_pkey'),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        op.f('ix_roadmap_features_updated_at'),
        'roadmap_features',
        ['updated_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_features_id'), 'roadmap_features', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_roadmap_features_deleted_at'),
        'roadmap_features',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_features_created_at'),
        'roadmap_features',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_features_column_id'),
        'roadmap_features',
        ['column_id'],
        unique=False,
    )
    op.create_table(
        'roadmap_feature_tags',
        sa.Column('feature_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'deleted_at',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'priority', sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['feature_id'],
            ['roadmap_features.id'],
            name=op.f('roadmap_feature_tags_feature_id_fkey'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['tag_id'],
            ['roadmap_tags.id'],
            name=op.f('roadmap_feature_tags_tag_id_fkey'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('roadmap_feature_tags_pkey')),
        sa.UniqueConstraint(
            'feature_id',
            'tag_id',
            name=op.f('uq_feature_tag'),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f('ix_roadmap_feature_tags_updated_at'),
        'roadmap_feature_tags',
        ['updated_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_feature_tags_tag_id'),
        'roadmap_feature_tags',
        ['tag_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_feature_tags_id'), 'roadmap_feature_tags', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_roadmap_feature_tags_feature_id'),
        'roadmap_feature_tags',
        ['feature_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_feature_tags_deleted_at'),
        'roadmap_feature_tags',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_roadmap_feature_tags_created_at'),
        'roadmap_feature_tags',
        ['created_at'],
        unique=False,
    )
    op.drop_index(
        op.f('ix_roadmap_action_item_tags_updated_at'),
        table_name='roadmap_action_item_tags',
    )
    op.drop_index(
        op.f('ix_roadmap_action_item_tags_tag_id'),
        table_name='roadmap_action_item_tags',
    )
    op.drop_index(
        op.f('ix_roadmap_action_item_tags_id'), table_name='roadmap_action_item_tags'
    )
    op.drop_index(
        op.f('ix_roadmap_action_item_tags_deleted_at'),
        table_name='roadmap_action_item_tags',
    )
    op.drop_index(
        op.f('ix_roadmap_action_item_tags_created_at'),
        table_name='roadmap_action_item_tags',
    )
    op.drop_index(
        op.f('ix_roadmap_action_item_tags_action_item_id'),
        table_name='roadmap_action_item_tags',
    )
    op.drop_table('roadmap_action_item_tags')
    op.drop_index(
        op.f('ix_roadmap_action_item_integrations_updated_at'),
        table_name='roadmap_action_item_integrations',
    )
    op.drop_index(
        op.f('ix_roadmap_action_item_integrations_integration_id'),
        table_name='roadmap_action_item_integrations',
    )
    op.drop_index(
        op.f('ix_roadmap_action_item_integrations_id'),
        table_name='roadmap_action_item_integrations',
    )
    op.drop_index(
        op.f('ix_roadmap_action_item_integrations_external_id'),
        table_name='roadmap_action_item_integrations',
    )
    op.drop_index(
        op.f('ix_roadmap_action_item_integrations_deleted_at'),
        table_name='roadmap_action_item_integrations',
    )
    op.drop_index(
        op.f('ix_roadmap_action_item_integrations_created_at'),
        table_name='roadmap_action_item_integrations',
    )
    op.drop_index(
        op.f('ix_roadmap_action_item_integrations_action_item_id'),
        table_name='roadmap_action_item_integrations',
    )
    op.drop_index(
        'idx_action_item_integration_external_id',
        table_name='roadmap_action_item_integrations',
    )
    op.drop_table('roadmap_action_item_integrations')
    op.drop_index(
        op.f('ix_roadmap_action_items_updated_at'), table_name='roadmap_action_items'
    )
    op.drop_index(op.f('ix_roadmap_action_items_id'), table_name='roadmap_action_items')
    op.drop_index(
        op.f('ix_roadmap_action_items_deleted_at'), table_name='roadmap_action_items'
    )
    op.drop_index(
        op.f('ix_roadmap_action_items_created_at'), table_name='roadmap_action_items'
    )
    op.drop_index(
        op.f('ix_roadmap_action_items_column_id'), table_name='roadmap_action_items'
    )
    op.drop_table('roadmap_action_items')
    # ### end Alembic commands ###
