"""project constraints and schema updates

Revision ID: 9dc669cd84cf
Revises: f68a1c687d01
Create Date: 2025-08-07 18:12:07.327447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9dc669cd84cf'
down_revision: Union[str, Sequence[str], None] = 'f68a1c687d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'projects',
        'deleted_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_index(op.f('ix_projects_deleted_at'), table_name='projects')
    op.create_unique_constraint(
        'uq_project_workspace_slug', 'projects', ['workspace_id', 'slug']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_workspace_slug', 'projects', type_='unique')
    op.create_index(
        op.f('ix_projects_deleted_at'), 'projects', ['deleted_at'], unique=False
    )
    op.alter_column(
        'projects',
        'deleted_at',
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    # ### end Alembic commands ###