"""empty message

Revision ID: 9dc669cd84cf
Revises: 12aa594305ee
Create Date: 2025-08-07 18:12:07.327447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9dc669cd84cf'
down_revision: Union[str, Sequence[str], None] = '12aa594305ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widgets',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('widget_type', sa.Enum('FEEDBACK', 'SURVEY', 'REVIEW', 'BUG_REPORT', 'FEATURE_REQUEST', 'NPS', name='widgettype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED', name='widgetstatus'), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('theme_configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('targeting_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embed_code', sa.Text(), nullable=True),
    sa.Column('public_key', sa.String(length=255), nullable=True),
    sa.Column('position', sa.Enum('BOTTOM_RIGHT', 'BOTTOM_LEFT', 'TOP_RIGHT', 'TOP_LEFT', 'CENTER', name='widgetposition'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_widgets_created_at'), 'widgets', ['created_at'], unique=False)
    op.create_index(op.f('ix_widgets_deleted_at'), 'widgets', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_widgets_id'), 'widgets', ['id'], unique=False)
    op.create_index(op.f('ix_widgets_public_key'), 'widgets', ['public_key'], unique=True)
    op.create_index(op.f('ix_widgets_updated_at'), 'widgets', ['updated_at'], unique=False)
    op.create_table('feedback',
    sa.Column('widget_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('feedback_type', sa.Enum('GENERAL', 'SURVEY', 'REVIEW', 'BUG_REPORT', 'FEATURE_REQUEST', 'NPS', 'CSAT', 'CES', name='feedbacktype'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', 'ARCHIVED', name='feedbackstatus'), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='feedbackpriority'), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitter_name', sa.String(length=255), nullable=True),
    sa.Column('submitter_email', sa.String(length=320), nullable=True),
    sa.Column('submitter_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('browser_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('is_spam', sa.Boolean(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('assigned_to_user_id', sa.UUID(), nullable=True),
    sa.Column('resolved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_feedback_deleted_at'), 'feedback', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_updated_at'), 'feedback', ['updated_at'], unique=False)
    op.create_table('bug_report_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('severity_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='feedbackpriority'), nullable=True),
    sa.Column('steps_to_reproduce', sa.Text(), nullable=True),
    sa.Column('expected_behavior', sa.Text(), nullable=True),
    sa.Column('actual_behavior', sa.Text(), nullable=True),
    sa.Column('environment_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['feedback.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feature_request_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('use_case', sa.Text(), nullable=True),
    sa.Column('business_value', sa.Text(), nullable=True),
    sa.Column('upvotes_count', sa.Integer(), nullable=True),
    sa.Column('downvotes_count', sa.Integer(), nullable=True),
    sa.Column('estimated_effort', sa.String(length=50), nullable=True),
    sa.Column('implementation_status', sa.String(length=50), nullable=True),
    sa.Column('roadmap_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['feedback.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('review_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('moderation_status', sa.String(length=50), nullable=True),
    sa.Column('reviewer_location', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['feedback.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('survey_type', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('response_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['feedback.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('projects', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_projects_deleted_at'), table_name='projects')
    op.create_unique_constraint('uq_project_workspace_slug', 'projects', ['workspace_id', 'slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_project_workspace_slug', 'projects', type_='unique')
    op.create_index(op.f('ix_projects_deleted_at'), 'projects', ['deleted_at'], unique=False)
    op.alter_column('projects', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_table('survey_feedback')
    op.drop_table('review_feedback')
    op.drop_table('feature_request_feedback')
    op.drop_table('bug_report_feedback')
    op.drop_index(op.f('ix_feedback_updated_at'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_deleted_at'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_widgets_updated_at'), table_name='widgets')
    op.drop_index(op.f('ix_widgets_public_key'), table_name='widgets')
    op.drop_index(op.f('ix_widgets_id'), table_name='widgets')
    op.drop_index(op.f('ix_widgets_deleted_at'), table_name='widgets')
    op.drop_index(op.f('ix_widgets_created_at'), table_name='widgets')
    op.drop_table('widgets')
    # ### end Alembic commands ###
