"""add workspace user name constraint

Revision ID: a1b2c3d4e5f6
Revises: 64caa391325b
Create Date: 2025-08-10 15:30:00.000000

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '64caa391325b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the old unique constraint on user_id
    op.drop_index('ix_workspaces_user_id', table_name='workspaces')

    # Add composite unique constraint on (user_id, name)
    op.create_unique_constraint(
        'uq_workspace_user_name', 'workspaces', ['user_id', 'name']
    )

    # Recreate user_id index without unique constraint
    op.create_index(
        op.f('ix_workspaces_user_id'), 'workspaces', ['user_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the composite unique constraint
    op.drop_constraint('uq_workspace_user_name', 'workspaces', type_='unique')

    # Drop the non-unique user_id index
    op.drop_index(op.f('ix_workspaces_user_id'), table_name='workspaces')

    # Recreate the old unique constraint on user_id
    op.create_index(
        op.f('ix_workspaces_user_id'), 'workspaces', ['user_id'], unique=True
    )
    # ### end Alembic commands ###
