"""handle created by in group model

Revision ID: a74472244fca
Revises: 1e758dd6f4ed
Create Date: 2025-07-16 22:10:00.508809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74472244fca'
down_revision: Union[str, None] = '1e758dd6f4ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('icon_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'icon_id')
    # ### end Alembic commands ###
