"""remove_circular_reference_feedback_roadmap

Revision ID: a9bb8977e47a
Revises: 73238fea42a8
Create Date: 2025-08-23 23:19:10.477986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9bb8977e47a'
down_revision: Union[str, Sequence[str], None] = '73238fea42a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_roadmap_features_feedback_id'), table_name='roadmap_features'
    )
    op.drop_constraint(
        op.f('roadmap_features_feedback_id_fkey'),
        'roadmap_features',
        type_='foreignkey',
    )
    op.drop_column('roadmap_features', 'feedback_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'roadmap_features',
        sa.Column('feedback_id', sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f('roadmap_features_feedback_id_fkey'),
        'roadmap_features',
        'feedback',
        ['feedback_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_index(
        op.f('ix_roadmap_features_feedback_id'),
        'roadmap_features',
        ['feedback_id'],
        unique=False,
    )
    # ### end Alembic commands ###
