"""add_priority_to_roadmap_features

Revision ID: b775b0aeb0a9
Revises: 868166a203cb
Create Date: 2025-08-24 17:24:21.786114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b775b0aeb0a9'
down_revision: Union[str, Sequence[str], None] = '868166a203cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'roadmap_feature_tags',
        sa.Column('priority', sa.String(length=20), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmap_feature_tags', 'priority')
    # ### end Alembic commands ###
