"""refer supabase for users from groups table instead of local

Revision ID: b857f814896c
Revises: e61bccdc6e85
Create Date: 2025-07-16 19:19:48.745531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b857f814896c'
down_revision: Union[str, None] = 'e61bccdc6e85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'group_members',
        sa.Column('group_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('group_id', 'user_id', 'id'),
    )
    op.create_index(
        op.f('ix_group_members_user_id'), 'group_members', ['user_id'], unique=False
    )
    op.alter_column(
        'groups',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'groups',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text('now()'),
    )
    op.drop_index('idx_groups_created_by', table_name='groups')
    op.create_index(
        op.f('ix_groups_created_by_id'), 'groups', ['created_by_id'], unique=False
    )
    op.drop_constraint('groups_created_by_id_fkey', 'groups', type_='foreignkey')
    op.drop_column('groups', 'icon_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'groups',
        sa.Column(
            'icon_id',
            sa.VARCHAR(),
            server_default=sa.text("'icon3'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_foreign_key(
        'groups_created_by_id_fkey', 'groups', 'users', ['created_by_id'], ['id']
    )
    op.drop_index(op.f('ix_groups_created_by_id'), table_name='groups')
    op.create_index('idx_groups_created_by', 'groups', ['created_by_id'], unique=False)
    op.alter_column(
        'groups',
        'updated_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.alter_column(
        'groups',
        'created_at',
        existing_type=postgresql.TIMESTAMP(),
        nullable=False,
        existing_server_default=sa.text('now()'),
    )
    op.drop_index(op.f('ix_group_members_user_id'), table_name='group_members')
    op.drop_table('group_members')
    # ### end Alembic commands ###
