"""Add form response v2 table

Revision ID: bb2c08cb87aa
Revises: 20e8dad7b149
Create Date: 2025-11-10 18:29:48.589301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb2c08cb87aa'
down_revision: Union[str, Sequence[str], None] = '20e8dad7b149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_responses_v2',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitter_email', sa.String(length=255), nullable=True),
    sa.Column('submitter_name', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms_v2.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_responses_v2_created_at'), 'form_responses_v2', ['created_at'], unique=False)
    op.create_index(op.f('ix_form_responses_v2_deleted_at'), 'form_responses_v2', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_form_responses_v2_form_id'), 'form_responses_v2', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_responses_v2_id'), 'form_responses_v2', ['id'], unique=False)
    op.create_index(op.f('ix_form_responses_v2_updated_at'), 'form_responses_v2', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_responses_v2_updated_at'), table_name='form_responses_v2')
    op.drop_index(op.f('ix_form_responses_v2_id'), table_name='form_responses_v2')
    op.drop_index(op.f('ix_form_responses_v2_form_id'), table_name='form_responses_v2')
    op.drop_index(op.f('ix_form_responses_v2_deleted_at'), table_name='form_responses_v2')
    op.drop_index(op.f('ix_form_responses_v2_created_at'), table_name='form_responses_v2')
    op.drop_table('form_responses_v2')
    # ### end Alembic commands ###
