"""add CoupleInvitationCode

Revision ID: cb7a2fdf05f5
Revises: 9627b90026ce
Create Date: 2025-07-29 22:21:43.209368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7a2fdf05f5'
down_revision: Union[str, None] = '9627b90026ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'couple_invitation_codes',
        sa.Column('code', sa.String(length=6), nullable=False),
        sa.Column('created_by_id', sa.UUID(), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('used_at', sa.DateTime(), nullable=True),
        sa.Column('used_by_id', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_couple_invitation_codes_code'),
        'couple_invitation_codes',
        ['code'],
        unique=True,
    )
    op.create_index(
        op.f('ix_couple_invitation_codes_created_by_id'),
        'couple_invitation_codes',
        ['created_by_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_couple_invitation_codes_created_by_id'),
        table_name='couple_invitation_codes',
    )
    op.drop_index(
        op.f('ix_couple_invitation_codes_code'), table_name='couple_invitation_codes'
    )
    op.drop_table('couple_invitation_codes')
    # ### end Alembic commands ###
