"""Increase logo_url max length to 100000

Revision ID: dc5767eef36c
Revises: remove_subscription_tier
Create Date: 2025-09-17 23:53:35.492292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc5767eef36c'
down_revision: Union[str, Sequence[str], None] = 'remove_subscription_tier'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_usage_tracking_organization_id'), table_name='usage_tracking'
    )
    op.drop_index(op.f('ix_usage_tracking_period_start'), table_name='usage_tracking')
    op.drop_index(op.f('ix_usage_tracking_resource_type'), table_name='usage_tracking')
    op.drop_table('usage_tracking')
    op.alter_column(
        'organizations',
        'subscription_plan',
        existing_type=sa.VARCHAR(length=20),
        type_=sa.Enum(
            'free',
            'pro_monthly',
            'pro_yearly',
            name='subscriptionplanenum',
            native_enum=False,
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'free'::character varying"),
    )
    op.alter_column(
        'organizations',
        'payment_status',
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Enum(
            'pending',
            'processing',
            'succeeded',
            'failed',
            'cancelled',
            'refunded',
            name='paymentstatusenum',
            native_enum=False,
        ),
        existing_nullable=True,
    )
    op.drop_column('roadmap_columns', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'roadmap_columns',
        sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.alter_column(
        'organizations',
        'payment_status',
        existing_type=sa.Enum(
            'pending',
            'processing',
            'succeeded',
            'failed',
            'cancelled',
            'refunded',
            name='paymentstatusenum',
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        'organizations',
        'subscription_plan',
        existing_type=sa.Enum(
            'free',
            'pro_monthly',
            'pro_yearly',
            name='subscriptionplanenum',
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        existing_server_default=sa.text("'free'::character varying"),
    )
    op.create_table(
        'usage_tracking',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            'resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            'usage_count',
            sa.INTEGER(),
            server_default=sa.text('0'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'period_start',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("date_trunc('month'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['organization_id'],
            ['organizations.id'],
            name=op.f('usage_tracking_organization_id_fkey'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('usage_tracking_pkey')),
        sa.UniqueConstraint(
            'organization_id',
            'resource_type',
            'period_start',
            name=op.f('uq_usage_tracking'),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f('ix_usage_tracking_resource_type'),
        'usage_tracking',
        ['resource_type'],
        unique=False,
    )
    op.create_index(
        op.f('ix_usage_tracking_period_start'),
        'usage_tracking',
        ['period_start'],
        unique=False,
    )
    op.create_index(
        op.f('ix_usage_tracking_organization_id'),
        'usage_tracking',
        ['organization_id'],
        unique=False,
    )
    # ### end Alembic commands ###
