"""Remove unused feedback fields

Revision ID: dd86d626b297
Revises: 4c82491b0d56
Create Date: 2025-10-02 21:23:54.116815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd86d626b297'
down_revision: Union[str, Sequence[str], None] = '4c82491b0d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_usage_tracking_organization_id'), table_name='usage_tracking'
    )
    op.drop_index(op.f('ix_usage_tracking_period_start'), table_name='usage_tracking')
    op.drop_index(op.f('ix_usage_tracking_resource_type'), table_name='usage_tracking')
    op.drop_table('usage_tracking')
    op.drop_column('bug_report_feedback', 'expected_behavior')
    op.drop_column('bug_report_feedback', 'visual_proof')
    op.drop_column('bug_report_feedback', 'steps_to_reproduce')
    op.drop_column('bug_report_feedback', 'actual_behavior')
    op.drop_column('ces_feedback', 'follow_up_comment')
    op.drop_column('csat_feedback', 'follow_up_comment')
    op.drop_column('feature_request_feedback', 'use_case')
    op.drop_column('feature_request_feedback', 'suggested_solution')
    op.drop_column('feature_request_feedback', 'benefits')
    op.drop_column('nps_feedback', 'follow_up_comment')
    op.drop_column('review_feedback', 'is_published')
    op.drop_column('review_feedback', 'pros')
    op.drop_column('review_feedback', 'cons')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'review_feedback',
        sa.Column('cons', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'review_feedback',
        sa.Column('pros', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'review_feedback',
        sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'nps_feedback',
        sa.Column('follow_up_comment', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'feature_request_feedback',
        sa.Column('benefits', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'feature_request_feedback',
        sa.Column('suggested_solution', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'feature_request_feedback',
        sa.Column('use_case', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'csat_feedback',
        sa.Column('follow_up_comment', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'ces_feedback',
        sa.Column('follow_up_comment', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'bug_report_feedback',
        sa.Column('actual_behavior', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'bug_report_feedback',
        sa.Column('steps_to_reproduce', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        'bug_report_feedback',
        sa.Column(
            'visual_proof',
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'bug_report_feedback',
        sa.Column('expected_behavior', sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        'usage_tracking',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            'resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            'usage_count',
            sa.INTEGER(),
            server_default=sa.text('0'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'period_start',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("date_trunc('month'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['organization_id'],
            ['organizations.id'],
            name=op.f('usage_tracking_organization_id_fkey'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('usage_tracking_pkey')),
        sa.UniqueConstraint(
            'organization_id',
            'resource_type',
            'period_start',
            name=op.f('uq_usage_tracking'),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f('ix_usage_tracking_resource_type'),
        'usage_tracking',
        ['resource_type'],
        unique=False,
    )
    op.create_index(
        op.f('ix_usage_tracking_period_start'),
        'usage_tracking',
        ['period_start'],
        unique=False,
    )
    op.create_index(
        op.f('ix_usage_tracking_organization_id'),
        'usage_tracking',
        ['organization_id'],
        unique=False,
    )
    # ### end Alembic commands ###
