"""added group icon

Revision ID: ea865626113f
Revises: 4d2f95717477
Create Date: 2025-07-13 00:39:50.469286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea865626113f'
down_revision: Union[str, None] = '4d2f95717477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'groups',
        sa.Column('icon_id', sa.String(), nullable=False, server_default='icon3'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'icon_id')
    # ### end Alembic commands ###
