"""add roadmap model

Revision ID: f62f34ac6069
Revises: 2e3f371c009b
Create Date: 2025-08-09 23:29:34.405770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f62f34ac6069'
down_revision: Union[str, Sequence[str], None] = '2e3f371c009b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'feedback_forms',
        sa.Column('project_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_feedback_forms_created_at'),
        'feedback_forms',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_feedback_forms_deleted_at'),
        'feedback_forms',
        ['deleted_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_feedback_forms_id'), 'feedback_forms', ['id'], unique=False
    )
    op.create_index(
        op.f('ix_feedback_forms_updated_at'),
        'feedback_forms',
        ['updated_at'],
        unique=False,
    )
    op.add_column('feedback', sa.Column('form_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'feedback', 'feedback_forms', ['form_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'form_id')
    op.drop_index(op.f('ix_feedback_forms_updated_at'), table_name='feedback_forms')
    op.drop_index(op.f('ix_feedback_forms_id'), table_name='feedback_forms')
    op.drop_index(op.f('ix_feedback_forms_deleted_at'), table_name='feedback_forms')
    op.drop_index(op.f('ix_feedback_forms_created_at'), table_name='feedback_forms')
    op.drop_table('feedback_forms')
    # ### end Alembic commands ###
