"""remove_feedback_status_column

Revision ID: f8bc6a7a8003
Revises: 28f14d572d1a
Create Date: 2025-09-19 15:47:56.240089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8bc6a7a8003'
down_revision: Union[str, Sequence[str], None] = '28f14d572d1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'status')
    op.drop_index(op.f('ix_roadmap_votes_user_id'), table_name='roadmap_votes')
    op.create_index(
        op.f('ix_roadmap_votes_created_at'),
        'roadmap_votes',
        ['created_at'],
        unique=False,
    )
    op.create_index(op.f('ix_roadmap_votes_id'), 'roadmap_votes', ['id'], unique=False)
    op.create_index(
        op.f('ix_roadmap_votes_updated_at'),
        'roadmap_votes',
        ['updated_at'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roadmap_votes_updated_at'), table_name='roadmap_votes')
    op.drop_index(op.f('ix_roadmap_votes_id'), table_name='roadmap_votes')
    op.drop_index(op.f('ix_roadmap_votes_created_at'), table_name='roadmap_votes')
    op.create_index(
        op.f('ix_roadmap_votes_user_id'), 'roadmap_votes', ['user_id'], unique=False
    )
    op.add_column(
        'feedback',
        sa.Column(
            'status',
            postgresql.ENUM(
                'NEW',
                'IN_PROGRESS',
                'RESOLVED',
                'REJECTED',
                'ARCHIVED',
                name='feedbackstatus',
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
